### ISSUE TITLE
APIView - Add a feature to lock comments to be resolved by originator only

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#1021]
Comments can be marked as resolved by any user in Azure-sdk org. Sometimes this is not correct when reviewer wants to validate it before marking it as resolved. It makes it difficult for reviewer to check all resolved comments to see if it actually resolved. 

This feature request from @JonathanGiles  is to support a locking mechanism for comments which ensures any comments originally made by a user can only be marked as resolved by that user. Any one else can mark it as `ready to resolve` or 'Request to resolve`

One assumption here is that this will be applied only for comments started by user. To start with, We can have this as an option to select as part of each comment whether it can be resolved by anyone or only originator.

@pakrym : just fyi on this feature request.

**Comment by pakrym** [comment]
One thing to consider is that some people leave a comment and never come back so allowing only them to resolve it would force the review author to chase them around.

**Comment by praveenkuttappan** [comment]
@pakrym :Agreed. This change should be at comment level rather than at review level and it's optional if reviewer think its critical and her needs to revisit the solution when it's ready to resolve. If reviewer is not planning to revisit and approve he can leave that option unchecked when making comments( This will be default behavior to keep it as it is now).

Additional option( may be a bit overkill at this point)
Alternatively we can have a feature to `Request Approval` of review that sends an email to all reviewers who commented on that review with a link to review. But this needs more thought on how we want to implement approval workflow. I know one of the road map item is to verify if review is approved or not before releasing package.

**Comment by Baas-hub** [comment]
I'll be picking up this issue shortly. Currently my plan for the implementation is as follows:
- The `thread head` (initial comment) will have an option on posting that will be something like "Allow anyone to resolve" (Default on, to preserve current workings)
- If this feature is on, anyone not the poster of "thread head" will no longer get access to the resolve option (this does base on the assumption that the thread discusses only one issue)
- Potentially also have an option to toggle the resolution openness in the drop down menu, so that it can be altered down the line (or on current/old comments).

This actual implementation would go approximately along the lines of:
- Add "thread head" user to the CommentThreadModel on page load (based on the initial comment's poster)
- On the Comment Form partial, add new checkbox for the openness of resolutions (and this'll flow up the comments manager tree, to a AllowOpenResolution variable in the comment class). Ideally this option would only be for the initial comment, and be automatically set for future comments.
- If desired, also add a similar option to the dropdown menu (also managed by the comment manager, by adding ToggleOpenness function)
- Add if-else statements to the Comment Thread Partial to display the different options based on the resolution openness selected

**Comment by Baas-hub** [comment]
Hi @praveenkuttappan, I am currently trying to work out a way to only show a button (the resolution button) to those on the approvers list (those who can approve reviews, that is) so that they can always mark comments as resolved.
I have tried using the `asp-requirement="@ApproverRequirement.Instance"` line in this form, but it did not enforce the requirement before showing the button, allowing everyone to see it again. After that, I've been unable to find where the approvers are kept other than the configuration.

Is there a way to enforce the approver requirement in the _CommentThreadPartial.cshtml file from the current models/system in place, or would I have to add the list of approvers to the thread models for threads that are resolution locked? (Ideally, I would like to avoid this as it would mean the configuration is passed through a lot more files than usually needed.)

**Comment by praveenkuttappan** [comment]
Let me take a look at this. Approver requirement should be good enough to hide.

**Comment by JonathanGiles** [comment]
@praveenkuttappan Any further thoughts here?

**Comment by praveenkuttappan** [comment]
@Baas-hub I was able to hide `Resolve` using below change. Please refer this to integrate with your change. You can actually create another Authorization check like Approver check which can include handling language check as well.
```
 <span asp-resource="@Model" asp-requirement="@ApproverRequirement.Instance">
                        @if (Model.IsResolved)
                        {
                            <form data-post-update="comments" method="post" asp-controller="Comments" asp-action="Unresolve" asp-route-reviewId="@Model.ReviewId">
                                <button type="submit" name="submit" value="Submit" class="btn btn-outline-dark">Unresolve</button>
                            </form>
                        }
                        else
                        {
                                <form data-post-update="comments" method="post" asp-controller="Comments" asp-action="Resolve" asp-route-reviewId="@Model.ReviewId" asp-requirement="@ApproverRequirement.Instance">
                                <button type="submit" name="submit" value="Submit" class="btn btn-outline-dark">Resolve</button>
                            </form>
                        }
                        <div class="comment-navigation-buttons">
                            <!-- Navigation button are added via JavaScript-->
                        </div>
                        </span>
                        ```
