### ISSUE TITLE
Use pre-installed Az PowerShell module rather than downloading from PSGallery

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#1051]
Last night we saw the following [error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=554965&view=logs&j=bb2b6fee-45a8-512d-234a-594e3a69db46&t=7c3de20e-d0dd-520b-3cf1-20995adccd99&s=b15d9194-8f26-5328-b47f-5968c76b37e7). 

Now, the pshell installer module already retries an download/install 3 times if it hits an exception. The issue here is that the repository threw a false-negative, which ended up crashing our pipeline. 

Whether wrapping the entire script in a retry-loop is the solution, I'll leave up to the implementer.

**Comment by weshaggard** [comment]
This goes a little larger then smok-tests I've see it fail for normal live test runs as well. We need to come up with some way to reduce this error path when powershell gallery isn't responsive.

**Comment by weshaggard** [comment]
Looks like at least hosted image already includes these PS modules (https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#azure-powershell-modules) and we should try to use those instead of always doing a force install. From a quick look it seems windows and linux have 4.7 and mac has 4.6.1 and as long as those versions are enough we should just use those instead of install anything.

**Comment by mikeharder** [comment]
Fixed by #1137
