### ISSUE TITLE
Flaky Resource Deployment: A hash conflict was encountered for the role Assignment ID

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#1240]
Test resource deployment occasionally fails with the following error:

```
"error": {
    "code": "DeploymentFailed",
    "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
    "details": [
    {
        "code": "HashConflictOnDifferentRoleAssignmentIds",
        "message": "A hash conflict was encountered for the role Assignment ID. Please use a new Guid."
    }
    ]
}
```

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=635858&view=logs&j=073ebbf1-9390-59a1-0ff8-08c656576bcd&t=8f3deacd-d82a-594d-00b3-f5cb2a881c2f&l=12714

This might be an issue in the CLI or the service:

https://github.com/Azure/azure-cli/issues/13368

We should investigate if there is a fix or workaround for this (maybe just add retries), including possibly asking the service team(s) to investigate on their side.

**Comment by benbp** [comment]
Context: this is either a re-use issue with the test-resources.json template and its usage of the role assignment, or a weird ARM guid expression bug.

Problem guid generation: https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/test-resources.json#L92. The accountname string should be unique since it's based off BaseName, which itself is a guid generated by New-TestResources.ps1.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-string?tabs=json#guid

**Comment by benbp** [comment]
This does not appear to be an issue anymore, as the tests have consistently passed since the filing of this issue. Closing unless we see it come up again.

**Comment by danieljurek** [comment]
@benbp -- Got another hit on this one: https://github.com/Azure/azure-sdk-for-cpp/pull/1951#issuecomment-804431902 

Source file has 2 role assignment objects but they are uniquely named: https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/test-resources.json#L72
