### ISSUE TITLE
Change the readme author to right owner and service to the right service name

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#1416]
https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/1067/files#r574784578

What we use currently:
Hard-coded Author: Maggie
Hardcoded Service: Azure

Proposed changes:
Author: the one who run the pipeline
Service: package name

**Comment by maorleger** [comment]
Thanks for this info! For this usecase I think what we are looking for is the idea of a primary owner... like if a nightly build fails, it's fine to send notifications to everyone listed as a codeowner, but when an issue is created for it and there are 5 owners (some of whom are just generic catch-all like Ramya and Deya) who should get assigned to the issue?

Maybe there's no great way to use CODEOWNERS for this, it's just that it's enticing because it's already there and is contiguously updated.

Do you or @weshaggard have any suggestions? I'd love to hear about them! If there isn't that's fine too - we have a separate list that I maintain for them, it's just the duplication is not ideal...

The need I'm trying to resolve is: is there a source vendors can lookup the right person to assign a nightly build failure to instead of a duplicated list? Is there a way to use CODEOWNERS for this (if we organize it so that the primary owner is listed first)?

**Comment by weshaggard** [comment]
I don't like maintaining a separate list of primary owners. I would much prefer we update our codeowners docs and just use the convention of the first one is the primary owner.

**Comment by sima-zhu** [comment]
Currently, we have already written the github code owner into metadata 'author' using 'retrieve-codeowners' tool.

For `ms.author`, we plan to use opensource API for github<->msalias

**Comment by sima-zhu** [comment]
Proposal:
1. Having two scripts:
`generate-aadToken.ps1`: The script is to generate token using necessary attributes.
`github-ms-converter.ps1`: The script takes in the add token + github name, returns the msAlias (userPrincipleEmail) which is calling opensource Rest API.

2. Have a helper class
MsNameResolver.cs: Input and output are same as script but using c# for implementation. The class serves as helper class.
