### ISSUE TITLE
Use taxonomy for service metadata

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#1442]
Our strategy for naming the service is currently: https://github.com/Azure/azure-sdk-tools/blob/master/eng/common/scripts/update-docs-metadata.ps1#L53 

However there is an official taxonomy of names for services. We should use the names from that taxonomy and only generate the service name as a fallback when a taxonomy-compliant name is not found.

**Comment by scbedd** [comment]
For future reference for anyone else looking at this issue. [Taxonomies are recorded here](https://review.docs.microsoft.com/en-us/help/contribute/metadata-taxonomies?branch=master#role).

Unfortunately we can't simply reach out and pull HTML here, as it is not a publically available page.

**Comment by scbedd** [comment]
Going to update our _releases/latest CSVs with a new column: `DocsSlugId`

**Comment by danieljurek** [comment]
Recently heard from the docs team about this issue. @weshaggard -- Would the docs slug id that goes in the `ms.service` ([example](https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/analytics.synapse.spark-readme-pre.md?plain=1#L11)) field be a good fit for the release preparation script?

**Comment by weshaggard** [comment]
As in you want folks to provide it when they run prepare-release? I suspect most folks will have no idea what value to give here. Ideally, we would derive it from one of our other pieces of metadata but if we cannot and it is unique, we can consider adding the value to the csv metadata file but we would need to figure out how to populate it.

**Comment by kurtzeborn** [comment]
We now have some of the things we were thinking of in this issue already done.  We are storing the data, we do verification similar to this for samples.

Keeping this open since we would still like this.  Limited customer impact.  Better grouping and searching probably which would help discovery.  Reporting would also be improved.

**Comment by JasonWHowell** [comment]
Learn uses a taxonomy that has a public endpoint at 
https://taxonomy.docs.microsoft.com/taxonomies/ms.service 
https://taxonomy.docs.microsoft.com/taxonomies/ms.prod

**Comment by JasonWHowell** [comment]
The code mentioned overriding the default metatadata by adding entries into the CSV. 

Thinking these are the packages to do the override in:
https://github.com/Azure/azure-sdk/edit/main/_data/releases/latest/*.csv

The **MSDocService** column is near the far right in each .csv file: `... ,"MSDocService","ServiceId","Notes"`

**Comment by nickwalkmsft** [comment]
Hi all - found this issue via the below while poking around looking at how MSDocService is applied: https://github.com/Azure/azure-sdk-tools/blob/0e13e3b715559a0e6a481d98beaf95be4ecf51ee/eng/common/scripts/Helpers/Metadata-Helpers.ps1#L50

I've got eyes on this now from the docs side. Old taxonomy values, particularly in ref content, are a persistent thorn in the side of the folks in charge of reporting.

One question I have about this is the scope of application - I'm not intimately familiar with all of the azure-sdk-tools automation, but following a couple threads in the source it looks like the MSDocService value from the CSV is only applied to readmes. The majority of the files have metadata applied via globs in docfx.json (see [here](https://github.com/Azure/azure-docs-sdk-dotnet/blob/738314a901bff91abf3603f0d8822a6459127127/docfx.json#L223)). **Does any of the automation touch that?**

The use of docfx.json works out fairly well, because that structure is relatively visible and a well-known way of applying metadata. For example, whenever there's a change to a taxonomy value, there's a service that roams around docs repos and attempts updates wherever it can find the old value. We recently just had a batch of such changes, which is why PRs like [this one](https://github.com/Azure/azure-docs-sdk-dotnet/pull/2488) are showing up everywhere. That works, including in the SDK repos, as far as I can tell, but the stuff going on in the CSV files is invisible to it - so I'm interested if the Azure SDK team's automation is going to come by and undo those changes.

cc @JimSuplizio

**Comment by JasonWHowell** [comment]
@nickwalkmsft When my team changed the CSV based values in the past, it did apply to the pages in the various SDK pages that are generated. Seems like on-page values would override docfx.json values. Maybe that makes it better to leave the CSV ms.services NULL and let the Docfx.json do all the heavy lifting?  It'd be good to figure this out, since the major reset of azure ms.services this month has all reference repos in limbo.

**Comment by danieljurek** [comment]
> The majority of the files have metadata applied via globs in docfx.json (see [here](https://github.com/Azure/azure-docs-sdk-dotnet/blob/738314a901bff91abf3603f0d8822a6459127127/docfx.json#L223)). Does any of the automation touch that? 

No automation on the Azure SDK side makes changes to metadata in docfx.json. Our automation only applies changes to the metadata in the package and service level overview .md files. https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/main/docs-ref-services/latest/storage-blob-readme.md?plain=1#L7


The `ms.service` value can change outside the scope of a package release. Our automation works primarily on package releases and we expect the user to provide a value for `ms.service` which ultimately ends up in a given metadata CSV file. If the correct value for a given package changes outside the scope of a release then we don't have a mechanism for updating that at this time. 

Automated updates to docfx.json might be a good way to do this as it would decouple changes to `ms.service` from our markdown files (which we only expect to update on package releases). 

@JimSuplizio, @nickwalkmsft, @JasonWHowell

**Comment by JimSuplizio** [comment]
@nickwalkmsft and I chatted about this, and this is going to be closed on our end. We, on the Engineering System, work with binaries and outside of the MSDocService in the CSV files, we don't really know what maps to what. There's no good way to plug into the taxonomy service to get this type of information which is why it's in the CSV file. Anything we do would require storing some kind of mapping which is something we already do with the CSV file entries. The next time [azure-sdk-tools/eng/common/scripts/Helpers/Metadata-Helpers.ps1](https://github.com/Azure/azure-sdk-tools/blob/0e13e3b715559a0e6a481d98beaf95be4ecf51ee/eng/common/scripts/Helpers/Metadata-Helpers.ps1#L50) needs to be touched, that TODO is going to be removed.

**Comment by nickwalkmsft** [comment]
👍  I'll look into whether it's realistic to move this into docfx.json or something else creative.
