### ISSUE TITLE
Explicit Subscription is not being used if user has another subscription selected

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#1454]
After #1405 some users are reporting issues where the `-Subscription` they pass is being ignored if their `AzContext` was from a different subscription. We may need to explicitly `Select-AzSubscription` and/or make sure it's passed to `Login-AzAccount` if provided.

Workaround is to make sure they have selected the same subscription via `Select-AzSubscription`, or log out of all contexts and log back in with the right subscription if logged in multiple times.

Ideally, users shouldn't specify this. Just make sure you're logged into the right sub. This was meant for CIs.

**Comment by apattath** [comment]
I ran into this issue today - see below for list of commands I ran. I sync'ed with Heath offline and the only workaround that worked for me was to run `Logout-AzAccount`, `Login-AzAccount`, followed by running `New-TestResources.ps1 -ServiceDirectory 'communication' -SubscriptionId <id>`. Specifically, I had to explicitly pass subscription Id to the New-TestResources script.

`PS H:\apattath_repo\azure-sdk-for-net> Connect-AzAccount -SubscriptionId '196d0816-62a1-41ca-9035-eb00a9cda249'
Account                  SubscriptionName         TenantId                             Environment
-------                  ----------------         --------                             -----------
avin.pattath@hotmail.com Visual Studio Enterprise 59cbf18d-9aa7-4912-b2fd-90e6c930173e AzureCloud
PS H:\apattath_repo\azure-sdk-for-net> .\eng\common\TestResources\New-TestResources.ps1 -ServiceDirectory 'communication' -BaseName 'avinpSdkLiveTestACS'
3:29:10 PM - Detected .NET repository. Defaulting OutFile to true. Test environment settings would be stored into the file so you don't need to set environment variables manually.
3:29:10 PM - TestApplicationId was not specified; loading cached service principal '3fe34569-0714-4dc1-955c-9de53be2a0fa'
3:29:11 PM - Logging into service principal '3fe34569-0714-4dc1-955c-9de53be2a0fa'
WARNING: The access token is from the wrong issuer 'https://sts.windows.net/59cbf18d-9aa7-4912-b2fd-90e6c930173e/'. It must match the tenant 'https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
WARNING: Attempt 1 failed: Exception calling "Invoke" with "0" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The provided account 3fe34569-0714-4dc1-955c-9de53be2a0fa does not have access to subscription ID "faa080af-c1d8-40ad-9cce-e1a450ca5b57". Please try logging in with different credentials or a different subscription ID.". Trying again in 10 seconds...`

**Comment by heaths** [comment]
I'm also testing this as documented using my personal MSA this time as well. I'll test against other subs in our Microsoft tenant as well to simulate other teams who don't have access to our subs for Azure SDK.

/cc @jsquire @benbp
