### ISSUE TITLE
[APIView Python] duplicate kwargs generated if there's a default in the method signature, but not in the sphinx docstring

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-tools#1528]
hey @praveenkuttappan 

this code:
<img width="866" alt="Screen Shot 2021-03-30 at 3 54 03 PM" src="https://user-images.githubusercontent.com/43154838/113048122-2bac2a00-9170-11eb-8331-92026281c66f.png">

is generating this in the apiview (search `build_classificationrules_create_or_update_request` [here](https://apiview.dev/Assemblies/Review/6abafb3120fb4063b09df0f2303a4ef9)). 

My understanding is sphixn docs don't have this information about the default, so would it be possible to ignore the typing in the sphinx docs in this situation?

**Comment by scbedd** [comment]
Take method signature over the docstring from sphinx. Method signature is the way.

**Comment by praveenkuttappan** [comment]
I think @tjprescott has a fix for this issue. Please confirm.

**Comment by tjprescott** [comment]
I think this should address your issue:
https://github.com/Azure/azure-sdk-tools/pull/2208

Specifically these lines:
![image](https://user-images.githubusercontent.com/5723682/140581330-2c1fddcb-2aaf-4167-b938-e2b3240ef5c5.png)

It will basically take the default from the docstring and, if not present, then the signature.  And the _reason_ it does this is because there's specific logic in the docstring parser to represent optional keywords with "= ...". I assumed it was some kind of shorthand that people requested, but this thread makes me not so sure. :)

I'm happy to change it if I understand what folks really want it to say.

**Comment by tjprescott** [comment]
@iscai-msft if you are talking about this:
![image](https://user-images.githubusercontent.com/5723682/140581851-5584ad04-50e1-499a-a13b-992b3f912b5e.png)

Yes my PR will fix that. It will show the second version (with the ...)

**Comment by tjprescott** [comment]
I just realized this is an old issue 😅  thought it was new.
