### ISSUE TITLE
Add condition check for the set-default-branch yaml 

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#1554]
The set-default-branch step failed because of the permission issue.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=838864&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9

Need to add condition check to turn it off if necessary

**Comment by weshaggard** [comment]
I don't think turning it off is the correct solution. For private repositories we likely need to pass in a token in order to be able to retrieve the default branch. We might be able to use the default System.AccessToken but if not we may need to condition this on passing another pat token value as an option.

**Comment by sima-zhu** [comment]
Never fail the pipeline. If not set, set it to master.

**Comment by sima-zhu** [comment]
The fix is in master. Closed the issue. We can open new issue if more changes needed.
