### ISSUE TITLE
Need a better error message for missing readmes in analyze step.

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-tools#1668]
If we can run the checks in the Analyze steps locally, that should be documented in https://aka.ms/azure-sdk-analyze-failed 

cc @praveenkuttappan, @chidozieononiwu

**Comment by kurtzeborn** [comment]
Instead of having an all-encompassing wiki page where we try to collect all of the things that could go wrong and describe how to run them locally, we've been taking a different approach where we try to have very descriptive errors which tell you how to unblock yourself when you see them.  What errors specifically were concerning you?  Let's try to improve those.

**Comment by ramya-rao-a** [comment]
In my case, I hit the "missing readme detected at" scenario. The docsetting.yml had a section for "known content issues" but not "known presence issues". Since I was multi tasking, my brain did not grasp the fact that they are two separate sections. So, I ended up doing a trial and error in adding the exception for the missing readme in the other two sections ("known content issues" and "omitted paths", pushed other changes and wait for CI. 

I would expect each of the checks a CI does to be doable locally as well so that we don't have to wait for CI to be triggered, and so this issue.

**Comment by ramya-rao-a** [comment]
If we want to focus on making the errors more actionable, then instead of a pointer to https://aka.ms/azure-sdk-analyze-failed, I would expect the error message to tell me (in my case) to add the path to the "known_presence_issues".

**Comment by praveenkuttappan** [comment]
I think @scbedd and I had created similar wiki for python about all the tests we do in Engsys and how to run those tests locally. Python definitely has the benefit of `tox`  I am guessing Ramya is looking for similar info. Instead of having a wiki link specific to a job like `Analyze`, I think we should think towards Engsys for JS wiki.

**Comment by kurtzeborn** [comment]
I've narrowed the title to something actionable.  @scbedd, you implemented this process previously, could you please take a look at improving this error message?

**Comment by kurtzeborn** [comment]
This feels pretty low on the priority list at this point.  Closing.
