### ISSUE TITLE
Consider using the sparse checkout in Create release tag

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#1686]
It would make it so the build takes seconds instead of minutes.
cc @benbp

**Comment by pakrym** [comment]
![image](https://user-images.githubusercontent.com/1697911/121584248-224c0300-c9e6-11eb-87cc-6e4074e13abe.png)

**Comment by benbp** [comment]
@pakrym I think this issue probably belongs in the net repo, as the changes need to be made there. Here's a PR for it: https://github.com/Azure/azure-sdk-for-net/pull/21789

FYI I recently went in and optimized the java release to use sparse checkout wherever possible, cutting about 15 minutes off the total time. NET should already have about 4 of those minutes cut off as of the last cycle, since I added sparse checkout for cloning the docs repository in azure-sdk-tools. I plan to get to the rest of the NET repo at some point soon, but it gets more complex as we need to detect which directories and filetypes are needed for various jobs.
