### ISSUE TITLE
New-TestResources.ps1 should automatically detect and use bicep files

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#1712]
Right now this script only looks for `test-resources.json` in the service directory. We are using bicep files because they are awesome, but this requires us to convert the bicep files to ARM json via CLI/PS.  It would be very handy to simply have the script detect and use the bicep file. Otherwise we have a manual step of converting the bicep to JSON or we end up committing the JSON template to the repo, which creates confusion.

**Comment by tjprescott** [comment]
cc/ @benbp

**Comment by benbp** [comment]
Digging into this a little bit, it's slightly more complex than I thought:

1. Azure Powershell can deploy from bicep files, as expected, however...
2. Our test-resources infrastructure defines a lot of extra configuration parameters for use across various ARM template deployments. In cases where these parameters don't match up 1:1 with the parameters defined in the template, validation will fail. So the current behavior of the script is to [parse the ARM template json and only pass in the parameters it defines](https://github.com/Azure/azure-sdk-tools/blob/154d977720f56e6816fb99e1e6ff6970321dda8a/eng/common/TestResources/New-TestResources.ps1#L436-L439).
3. This is not as easy to do in the script with bicep files, since they aren't json and we would need to do some manual parsing (likely a regex for `param <name>` but it feels like there could be potential issues with that).
4. The obvious solution is to build the bicep files first, and then run the parameter parsing code over the outputted arm template json file. However, bicep does not yet have any powershell support for the equivalent of `az bicep build`. I do not want to introduce an azure cli dependency into the `New-TestResources.ps1` script.

I'm going to see if I can find out more information about whether any bicep work is in progress for powershell. If it's not going to be any time soon, I think our two options are to either manually parse the main bicep file, or introduce an azure cli dependency.

**Comment by benbp** [comment]
Adding on to ^^, it looks like bicep has a [standalone CLI](https://github.com/Azure/bicep/blob/main/docs/installing.md#install-and-manage-via-azure-powershell) (which apparently you need to have in path for Az powershell deployments to work anyway).

So I think what I'll do is error out of the script if the bicep command isn't in path, otherwise run a `bicep build` against the passed in file and then parse the outputted json for parameters. I believe bicep is pre-installed on the pipeline agents (e.g. [here](https://github.com/actions/virtual-environments/blob/dd399bcab41317bb4b1d92f32d816dfe95d4e474/images/linux/scripts/installers/bicep.sh)), so that will make this task easier.

**Comment by weshaggard** [comment]
If the commands require the cli anyway and you essentially are going to run the same command they would then I'm fine with that assuming the commands don't end up being crazy and they are pretty straight forward.

**Comment by benbp** [comment]
I've got a first pass up at https://github.com/Azure/azure-sdk-tools/pull/1767. It works for deploying bicep, but I want to do a lot more testing against existing stuff just to make sure it's not breaking anything.

**Comment by pakrym** [comment]
Doesn't seem to work: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=987960&view=logs&jobId=88b6defb-98d5-5c46-10d7-5c27d44a027b&j=88b6defb-98d5-5c46-10d7-5c27d44a027b&t=5a4d4d27-d067-5627-c0d2-6fe2fd35c3c7

**Comment by benbp** [comment]
@pakrym `bicep` isn't installed on mac agents yet. I wasn't expecting anyone to jump on this so soon, so my plan was to wait until the dependency is rolled out (it was just [checked in](https://github.com/actions/virtual-environments/blob/e8381d7db3a011a744a9d76eebb6e044327cfdae/images/macos/provision/core/bicep.sh) to the installer scripts yesterday). I assume it will take a few weeks to make its way to our agent pool.

If you want this sooner I can look into adding a task to run that script in the meantime. Let me know.

**Comment by pakrym** [comment]
I'm OOF next week. It can wait. Thanks for adding the feature.
