### ISSUE TITLE
resource deployment doesn't clean-up correctly when there are multiple deployments

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#1904]
Based on pipelines like the spring one, see error https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1047169&view=logs&j=6ddc3820-470e-5638-11a6-c1adaee6c311&t=2fb17bf8-5823-5206-f5c7-887b3d5da607. Ignore the specific error in that log that is handled separately but the main point of this issue is the fact that we call remove resources multiple times with the same resource group. Most likely the resource group we deployed last. We need to come up with a way to ensure we clean-up all the resource groups we deployed if we deploy more then one in a pipeline.

**Comment by mikeharder** [comment]
The root cause is here:

https://github.com/Azure/azure-sdk-for-java/blob/852c9eadb1ae8c13e936aa53a96002a933e38028/eng/pipelines/templates/jobs/live.tests.yml#L68

The code accepts a list of `TestResourceDirectories`, but multiple calls to `deploy-test-resources.yml` followed by multiple calls to `remove-test-resources.yml` doesn't work correctly, since they are trying to share state using a single set of env vars.

Two possible solutions:
1. `deploy` **appends** to an env var with a **list** of RGs to delete, and `remove` deletes all RGs in the list.  Pipelines would only call `remove` once, no matter how many times `deploy` was called.
2. `deploy` and `remove` use env vars which are scoped by the `ServiceDirectory` parameter.  Some of the env vars in `deploy` and `remove` are already scoped by `${serviceDirectoryPrefix}`, but `AZURE_RESOURCEGROUP_NAME` is not.  Pipelines would call `remove` for each call to `deploy`.

**Comment by weshaggard** [comment]
Another possible solution is write the list of resource groups to clean-up to a file that we could read in the clean-up script.
