### ISSUE TITLE
[Python APIView] Need to transition away from Python 3.6 by Jan 1st, 2022

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#2288]
Effective Jan 1st, 2022 we are dropping support for Python 2.7 and 3.6. We need to transition APIView to Python 3.7 or higher by this date.

cc/ @johanste @lmazuel

**Comment by johanste** [comment]
In general, we should make sure that we support extracting packages that require the latest version of Python in API View. While we have a common baseline for which version a package should support, there will be exceptions to the rule where a given package needs/takes advantage of features in a newer version (e.g. data classes etc.). Not being able to handle those packages will be a problem.

**Comment by kurtzeborn** [comment]
Since this is specific language parser support in ApiView this work should be owned by that language team. @praveenkuttappan will be available to consult/assist as needed.

**Comment by praveenkuttappan** [comment]
Current limitation is due to python version support inside Azure web app. Azure web app has python 3.6 extension only. I will check if we can upgrade python version somehow. But our long term goal is to move away from parsing wheel or source inside APIView server and generate token file by PR and CI pipeline. I am currently working on this solution. I am also working on a solution to support similar sandboxing approach for manual review upload and parser upgrades.

**Comment by lmazuel** [comment]
@praveenkuttappan I'm a little confused, as there is definiltey more Python available on Web App:
![image](https://user-images.githubusercontent.com/1050156/144938291-711da735-0a13-401f-bab2-03013224704c.png)
