### ISSUE TITLE
REST API repo pipeline should check directory structure

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#2298]
The PR pipeline in the azure-rest-api-specs repo should check that PRs follow the directory structure conventions outlined in the repo [README.md](https://github.com/Azure/azure-rest-api-specs/blob/main/README.md) and flag any discrepancies.

In particular, it should check that all files within `specification` have either `resource-manager` or `data-plane` as the third path segment.

I think the natural place to add this would be in [Avocado](https://github.com/Azure/avocado), but that is an implementation detail that can be decided by the engineering team.

**Comment by weshaggard** [comment]
FYI @akning-ms @zhenglaizhang 

I agree we need to start enforcing some better conventions in the structure of the specs repo. I was talking with @zhenglaizhang earlier this week about adding some code/tools that can traverse and discover metadata for a given api in support for our APIView work. As we start to normalize that discovery we can use that as an enforcement as well because if they don't follow the conventions we will not discover them and if we don't discover anything then it will be as if they don't exist and we can error if we find nothing. 

@akning-ms who would be a good person to assign this to?

**Comment by akning-ms** [comment]
Yes. Mike, Avocado will be natural tool to this check. in the mean time, maybe we should revisit current repo structure first as Wes said, and also like adding a common folder for each of RP etc.  
assign to Avocado owner @ruowan

**Comment by weshaggard** [comment]
I think for the time being we should align with the current guidelines at https://github.com/Azure/azure-rest-api-specs/blob/main/README.md#directory-structure, if we end up changing that then we can adjust the tools as well.

One thing that I've been noticing while examining different tools is we already make assumptions and reimplement discovery in lots of places in our tools and we should start looking into trying to consolidate that logic.

**Comment by ruowan** [comment]
@weshaggard  I will write a doc and summarize the current implementation, also find the difference from guidelines.

**Comment by ruowan** [comment]
I created a work item to track it.  https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1509875. Currently, there are already check for readme default tag and folder structure. https://github.com/Azure/avocado

**Comment by mikekistler** [comment]
I think [PR #7030](https://github.com/Azure/azure-rest-api-specs-pr/pull/7030) is a good example where Avocado is not flagging structure issues. In particular, this PR creates a new api-version, "2022-06-15-preview", but this new version is not referenced in the readme.md. Another problem is that a json file from the prior api-version, "2020-12-14-preview", is not carried forward into the new api-version.

I would like Avocado (or some other tool if necessary) to flag these things _AND_ to point the developer to documentation that explains the requirements clearly.

**Comment by ruowan** [comment]
Avocado will validate the swagger reference in readme.md. Here is the rule https://github.com/Azure/avocado#unreferenced_json_file. 

Also MISSING_API_IN_DEFAULT_TAG is disabled for data-plane swaggers. The reason is the data-plane apis and readme tag is more flexible than management-plane.  So @tianxchen-ms will investigate how to optimize this rule for data-plane and then we will enable it.

**Comment by ruowan** [comment]
For this PR https://github.com/Azure/azure-rest-api-specs-pr/pull/7030, @tianxchen-ms  will check why avocado doesn't report error.

**Comment by tianxchen-ms** [comment]
The command in pipeline is `./node_modules/.bin/avocado -f pipe.log --excludePaths "common-types" ".github" ".azure-pipelines" "documentation" "arm-compute" "profile" "profiles" "scenarios" "package.json" "package-lock.json" "cadl/examples"`. The json file named `certificateprofile.json` will be excluded. I will fix this in pipeline.
