### ISSUE TITLE
Add sovereign cloud compatibility linters to ARM/bicep templates

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#2316]
A recurring issue for adding sovereign cloud support is hardcoded references to public cloud endpoints, subscription ids, tenant ids, etc. It would be helpful to have a set of linters for CI when changes are made to ARM templates to warn against this class of issue.

**Comment by kurtzeborn** [comment]
Closing because this, while still a potential issue, happens much less often.  This is because the base templates being used have already been sanitized from having references to public clouds any more. So when they are copy/pasted to start a new template, they already start on the right foot.  Additionally, we now know to look for these in code reviews and so none are slipping through the cracks.
