### ISSUE TITLE
[API view] Enable tagging users in comments 

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-tools#2505]
When adding comments to APIs, enable tagging users with `@username` and send them an email notification.

**Comment by kurtzeborn** [comment]
@praveenkuttappan, not sure if this is UI or backend.  If it's UI, please reassign as appropriate.

**Comment by praveenkuttappan** [comment]
This requires change in backend as well. I will work with @chidozieononiwu once his current UI changes are completed.

**Comment by JonathanGiles** [comment]
I'm curious how we would map a Github username to a Microsoft email alias?

**Comment by Vailorium** [comment]
@JonathanGiles

**Comment by Vailorium** [comment]
@praveenkuttappan Looking for advice on this issue - what would be the best way to notify users they have been pinged? As far as I'm aware we would require the user being pinged to provide their token to get their private github email addresses, but that wouldn't work - is there a good workaround for this?

**Comment by praveenkuttappan** [comment]
No need to get their email address to ping. Just add them to subscriber list of the review so they will be notified automatically when anyone comments.

**Comment by praveenkuttappan** [comment]
1. One work around is to query email address using user ID and if it's publicly available then we can inform the user. So this requires a new API to be added in the backend to send email and we need to ensure this API is accessible only for authenticated users. 
2. If email address is private then we just can't do anything. Only option is to store User ID in this case and check for email address run time to find the email and send notification if it's available, otherwise skip it.

where is this notifier stored to send any follow up notifications?
For e.g. If reviewer tag me in the first comment, then I should get notifications for any further responses on that comment thread. right? Are we storing this user ID somewhere?

**Comment by Vailorium** [comment]
> 

@praveenkuttappan it stores the tagged user login strings (e.g. praveenkuttappan or Vailorium) in a hashset in the comment model, when handling notifications it (would) only send a notification to any new users added to this hashset (Jonathan suggested it be handled like this, but can be adjusted easily).

I thought about only using the user's public emails, but for most of the users I looked up, they didn't have one. 90%~ of users not receiving notifications from tags would defeat the point of this issue, I feel.

**Comment by JonathanGiles** [comment]
I would recommend we implement this properly in the way I outlined here: #4164
