### ISSUE TITLE
Have common contract for Docs.MS validation step 

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#2676]
We currently have return different format for different language at validation.

It brings us difficulty in checking the failure.

Will have validation function return the same thing and check the failure over there.

Failed pipeline:https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1343628&view=logs&j=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b&t=26ac1571-47fc-5d52-3897-39c8bdecf4db

**Comment by sima-zhu** [comment]
A valuable point to follow up
https://github.com/Azure/azure-sdk-tools/pull/2673#pullrequestreview-872310558

**Comment by danieljurek** [comment]
This issue is tracking work to "Make JS onboarding validation work the way Python and Java do" 

JS was the first attempt at this validation and ran all packages in parallel each time (performance is pretty good when building in parallel). This can be addressed when upgrading to use the new converter provided by the skilling team.

**Comment by danieljurek** [comment]
This work was done in 2023 https://github.com/Azure/azure-sdk-for-js/pull/27935/files#diff-1d28dc86baa237ca6efe6224431142a9e8bbff66fa10a2c20c69031a22f5b387L221 

The validation tool no longer runs over all entries in the onboarding file. Just the entries which will be changed.
