### ISSUE TITLE
Ability to add usage samples to API reviews

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-tools#285]
It would be great if usage sample, and other commentary, could be added to API review packets. This would make the tool into a one stop shop.

I can imagine the following experience:
1. When uploading a dll, the uploader can submit a an intro that shows at the begining of the listing. 
2. The intro section can be commented on just like API listing.
3. The intro section can have text and code samples.

Fancy features:
1. Each usage sample is a separate object (panel) and the beginning of the review shows TOC of the samples
2. The samples are verified/compiled for the most recent APIs.

**Comment by KrzysztofCwalina** [comment]
cc: @terrajobst, @pakrym

**Comment by JonathanGiles** [comment]
This would indeed be very useful!

**Comment by KrzysztofCwalina** [comment]
I think we should increase the priority of this work item. Reviewing usage samples is a part of our process, yet we don't have a structured way to submit them, comment on them, and manage them.

**Comment by JonathanGiles** [comment]
I agree. It would be nice to have a separate 'code samples' tab in each APIView, perhaps, that would allow the user to supply markdown formatted text, in the same way that today they might write a gist. It brings the samples far closer to the API.

**Comment by terrajobst** [comment]
A single markdown document might be sufficient for a start. The trick will be to figure out commenting in the end result.

**Comment by JonathanGiles** [comment]
I was discussing this with @praveenkuttappan as I have a group of student engineers working with me who may implement it. My current thinking of how this will work is the following:

1. All reviews will have a new tab (alongside conversation and revisions) for something like "documentation".
2. Going to this tab will give the user to either drag/drop a markdown file, or copy/paste markdown text, and submit this to APIView.
3. APIView will store this markdown file in blob storage alongside the review json file, with the same name as the review json file, except with the extension '.md' rather than '.json'
4. When the review page is loaded, it will check for the existence of the markdown file, and if present it will convert it to HTML and render it on the documentation page. 
5. Beneath the documentation there will be a UI to allow for comments to be left, in much the same way that GitHub gists allow for bottom-of-file commentary. 

The trade-off with this approach is that we will not be able to do line-by-line feedback of the usage samples, but it makes implementation drastically simpler. I'm keen to hear thoughts on trade-offs - would you rather the functionality I describe above existing ~soon, or would you rather have line-by-line commentary of the usage samples / other documentation?

Thoughts? // @KrzysztofCwalina

**Comment by Baas-hub** [comment]
I'll start working on this now @JonathanGiles

**Comment by Baas-hub** [comment]
@praveenkuttappan Can you please help me add https://github.com/xoofx/markdig as a dependency for the MD parsing in this issue?

**Comment by praveenkuttappan** [comment]
> @praveenkuttappan Can you please help me add https://github.com/xoofx/markdig as a dependency for the MD parsing in this issue?

Is there a released package from this repo? I prefer not to take a dependency on source which is very likely to cause a breakage when developer makes any breaking change in their repo. What exactly are we trying to achieve using this library?

**Comment by Baas-hub** [comment]
> > @praveenkuttappan Can you please help me add https://github.com/xoofx/markdig as a dependency for the MD parsing in this issue?
> 
> Is there a released package from this repo? I prefer not to take a dependency on source which is very likely to cause a breakage when developer makes any breaking change in their repo.

That makes sense. There is a NuGet package of the repo available here: https://www.nuget.org/packages/Markdig/
Is this suitable for including?

**Comment by praveenkuttappan** [comment]
Yes. Absolutely. So this link should help you add it as dependency to APIViewWeb project. [manage nuget package](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio)

**Comment by Baas-hub** [comment]
@praveenkuttappan 
Upon installing a library from NuGet that allows me to do syntax-highlighted code examples in usage samples I end up with this error:
![image](https://user-images.githubusercontent.com/28514942/183799840-33dd0ec3-56ee-4035-abe0-eb0fe9c04cb5.png)
Where there are conflicting namespaces. How can I get around this? (Currently using Markdig.SyntaxHighlighting, but most have the same issue.) The clash comes from Markdig.Signed, as opposed to plain Markdig, which share an indentical namespace.

**Comment by praveenkuttappan** [comment]
> @praveenkuttappan Upon installing a library from NuGet that allows me to do syntax-highlighted code examples in usage samples I end up with this error: ![image](https://user-images.githubusercontent.com/28514942/183799840-33dd0ec3-56ee-4035-abe0-eb0fe9c04cb5.png) Where there are conflicting namespaces. How can I get around this? (Currently using Markdig.SyntaxHighlighting, but most have the same issue.) The clash comes from Markdig.Signed, as opposed to plain Markdig, which share an indentical namespace.
> 
> Additionally, do you have a preference for where comments are stored? Currently the options I can think of are:
> 
> * In the same container as Review Comments (UsageSamples have unique ids)
> * In the same container as Usage Samples
> * In their own UsageSampleComments container

Let me check the error with markdig and I will get back to you.

And regarding sample comments:
I prefer to store it in same Comments container. One additional change we need to do is to add an extra bool flag in this comments record to identify whether a comment is for sample or code. Something like `IsSampleComment` and set it to true only for comments created for sample. This will help us differentiate in UI side and group code comments and sample comments in conversation tab.

**Comment by praveenkuttappan** [comment]
> > @praveenkuttappan Upon installing a library from NuGet that allows me to do syntax-highlighted code examples in usage samples I end up with this error: ![image](https://user-images.githubusercontent.com/28514942/183799840-33dd0ec3-56ee-4035-abe0-eb0fe9c04cb5.png) Where there are conflicting namespaces. How can I get around this? (Currently using Markdig.SyntaxHighlighting, but most have the same issue.) The clash comes from Markdig.Signed, as opposed to plain Markdig, which share an indentical namespace.
> > Additionally, do you have a preference for where comments are stored? Currently the options I can think of are:
> > 
> > * In the same container as Review Comments (UsageSamples have unique ids)
> > * In the same container as Usage Samples
> > * In their own UsageSampleComments container
> 
> Let me check the error with markdig and I will get back to you.
> 
> And regarding sample comments: I prefer to store it in same Comments container. One additional change we need to do is to add an extra bool flag in this comments record to identify whether a comment is for sample or code. Something like `IsSampleComment` and set it to true only for comments created for sample. This will help us differentiate in UI side and group code comments and sample comments in conversation tab.

I have found that APIViewWeb is already using MarkDig.Signed that was causing conflict when you tried to add Markdig dependency. I have submitted a PR to update Markdig.signed version to latest. We don't need Markdig. MArkdig.Signed is what we should use, and it's already linked to APIViewWeb project.

Please let me know if you are not able to get any specific feature. Ideally Markdig.Signed should have all features supported by MArkdig. It's just a signed nuget package. That's all.

Here is my PR to update version: https://github.com/Azure/azure-sdk-tools/pull/3914

**Comment by Baas-hub** [comment]
@praveenkuttappan I believe I misspoke initially, I am not adding Markdig itself as a dependency, but a new item, specifically "Markdig.SyntaxHighlighting". When this is added, VS/Nuget provide their own Markdig version, since it does not see Markdig.Signed as an appropriate dependency. This is where the errors occur.

I am not worried about the specific SyntaxHighlighting package I use, but I would appreciate help in getting at least one of them working with Markdig.Signed as opposed to Markdig. (Markdig.Signed does have everything, and is what I am using for the core of the project, but as Syntax Highlighting was requested also, I am working to include it.)

**Comment by praveenkuttappan** [comment]
> Markdig.SyntaxHighlighting

I see the issue now. Thanks for the clarification. This can be resolved if we remove `Markdig.Signed` from dependency and add `Markdig` and `Markdig.SyntaxHighlighting`. I have verified this and projects got built successfully.


1. Uninstall `Markdig.Signed` from dependency

2. Install '`Markdig.SyntaxHighlighting` and this will pull in `Markdig`.
