### ISSUE TITLE
Failing PR automation: Cross Version Breaking Changes

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#2919]
The Cross Version Breaking Changes check threw a runtime exception in PR #18170:

https://github.com/Azure/azure-rest-api-specs/pull/18170/checks?check_run_id=5499460450

![image](https://user-images.githubusercontent.com/85643503/158496268-5f80ef3a-a9dc-4f52-9d58-62336d9bd689.png)

**Comment by jianyexi** [comment]
this is because modeler1 does not support  syntax 'additionalProperties:true' , that's why autorest will transform it to 'additionalProperties:{}' by default , 
https://github.com/Azure/azure-rest-api-specs/blob/a81a1c17972846475e52d8843fc86993a0efdbaa/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2022-04-01-preview/Watchlists.json#L669
