### ISSUE TITLE
Simplify branch policies for azure-rest-api-specs repo

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#2929]
Today when creating dev branches in OpenAPIHub it create a unique branch protection for every branch which causes a number of issues. 
- Lots of branch protection policies that never get cleaned up
- Lots of branches that never get cleaned up because the polices block anyone that is not an admin from deleting
- Prevents teams from rebasing changes on main which causes a lot of noisy merges because the policy doesn't allow force push.

To help with these issues we should do the following:
- Create a single branch protection for any branches following the existing naming convention of `dev-*`.  (ideally we would update this naming convention to something like feature/* or release/* but there are so complications with so we will not change the existing naming convention with this work).
  - Policy should require CI checks and approval for merging
  - Policy should allow force pushes so teams can rebase and clean their branch in preparation for going to main
  - Policy should allow deletion of branches so that teams can remove their branch one all their work is done
- Clean-up all the existing branch protection policies to remove all the duplication

**Comment by weshaggard** [comment]
Yes Teams would include service teams or anyone working on a feature in the specs repo. 

Can you give me more details on why you think those are in conflict with one another? Even if we enable allowing force push all the other branch protection rules must still be followed, including required checks, see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#allow-force-pushes.

**Comment by weshaggard** [comment]
After some further testing @heaths and I concluded we cannot have "required status checks" and "allow force push" in the same branch protection rule. While you can check the options there is no real way for someone to do it because github will block force pushes when there are required status checks that have not been met. However we should still enable the "allow branch deletions" option so that teams can clean-up their branches.

**Comment by heaths** [comment]
Allowing force push is not the only reason to have blanket policies, though. @weshaggard helped me recently recover from an issue where an old OpenAPI Hub-created branch policy referenced a pipeline name that got renamed or otherwise differed from the required check name. That blocked the PR and required an admin to fix it. Presumably, any earlier branch policy would be impacted.

All the branch policies were, at one point, the same anyway. There's no special permissions on them, so why even create specific ones? By having just a small handful of branch policies that match patterns like `dev-*` it's far easier to maintain those policies when necessary.

That also starts to obviate the need to create a branch in OpenAPI Hub. Apart from creating the branch (which anyone with push permissions can otherwise do) and branch policy, it copies files and updates the api-version which anyone can also do. Recently, to create a new api-version from another api-version feature branch, I even created a [script to do this](https://gist.github.com/heaths/350485ab034f9da2bd10468dfcf2c794).

**Comment by raych1** [comment]
@weshaggard , I think the remained item for this issue is to clean up the other specific `dev-xx` policies with keeping only `dev-*` policy, right?

**Comment by weshaggard** [comment]
Assuming we have now updated openapi to not add the branch protections any longer then yes the last remaining part will be to delete all the old ones.

**Comment by raych1** [comment]
The change in openapi hub code will be released about next week. @weshaggard , will you help delete all the old policies from rest api spec repo?

**Comment by weshaggard** [comment]
@raych1 I can try and help if needed. Do you not have permissions to delete branch policies? If not perhaps @akning-ms can grant you permissions at least temporarily.

**Comment by raych1** [comment]
@weshaggard , can you help clean up the remained rules I sent to you in email?

**Comment by weshaggard** [comment]
Yes I will try to get those cleaned up this week.

**Comment by weshaggard** [comment]
This work is done now. The branch protections are much cleaner and easier to maintain now.
