### ISSUE TITLE
[Python APIView] APIView should not trigger a change for annotation change around None

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#2948]
![image](https://user-images.githubusercontent.com/1050156/159535128-513fa820-9c3c-4c0a-9875-28d942e934d4.png)

Technically, all methods returns None unless you ask to return something else, so I wonder in absence on any information in the return type, if APIView shouldn't expose it differently? I feel there is something to do here, but I'm unsure what (create this issue to brainstorm)

https://github.com/Azure/azure-sdk-for-python/pull/23441

**Comment by tjprescott** [comment]
It's strange that the diff would show "-> None" being _removed_ when it looks like the PR in question added it? I could simply make APIView infer return type "None" when there is no return type information, but it seems like it might be better to simply have a linter rule that enforces that all methods should specify a return type.

I opened an issue that tracks said rule here: https://github.com/Azure/azure-sdk-for-python/issues/23581

As far as the diff goes, that's all text-based on the web side, so if the text (or IDs) differ, it will show a diff.

**Comment by tjprescott** [comment]
We discussed this and the options would be:
1. No change. APIView renders a return type of None if the type checking reveals that (typehint or docstring). Make no inference around return types if not provided.
2. Infer a return type of `None` if not specified and display `-> None`. We could have a custom pylint check to detect a situation where no return type info is specified.
3. Infer a return type of `None` if not specified and display _nothing_ for the case AND also strip `-> None` if it would otherwise appear. Again, if we have a custom pylint check to ensure return type info is always provided, this would mean that any APIView method with no return type annotation would be implicitly a `None` return type.

**Comment by annatisch** [comment]
My preference would be that APIview always renders the return type, at that we use pylint to always enforce that a return type be specified. In other words, "Option no. 1".

I'm not a huge fan of inferring anything from omission - just in case the omission was accidental. Likewise, I like seeing the return types in APIview even if they're None.

Then, if a return type is missing - that would be a flag that something either slipped through the pylint rule, or it was formatted in a way the APIview couldn't understand and needs fixing either in the source or APIview.

**Comment by tjprescott** [comment]
Based on the recommendation to go with option 1 (i.e. no change) I am closing this issue. Please reopen if you feel it requires more discussion.
