### ISSUE TITLE
Is there a shared/managed app insights service?

### ISSUE THREAD

**Issue by j-martens** [Azure/azure-sdk-tools#33]
Our team is finally looking into trying this out. Do you know if the pixel server require us to run our own appinsights service, or if there is a managed option we can use?

cc: @vizhur @rastala @danielsc

**Comment by j-martens** [comment]
@weshaggard @chidozieononiwu Can you help answer this please?

**Comment by weshaggard** [comment]
@scbedd could you help with this question?

**Comment by scbedd** [comment]
@j-martens AppInsights by it's very nature is the managed option.

[Instructions on How to Create](https://docs.microsoft.com/en-us/azure/azure-monitor/learn/mobile-center-quickstart#create-an-application-insights-resource)

Did you glance through the [readme section](https://docs.microsoft.com/en-us/azure/azure-monitor/learn/mobile-center-quickstart#create-an-application-insights-resource) talking about AppInsights? Which piece should I enhance so that this is clearer to the user?

**Comment by j-martens** [comment]
@rastala - does this help? Can you set this up now?

Thanks @scbedd Scott. :-)

**Comment by j-martens** [comment]
@swinner95

**Comment by scbedd** [comment]
@swinner95 I'm closing this issue. You got it :)
