### ISSUE TITLE
Created JavaScript apiView diff is unexpected, which misses diffs

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-tools#3444]
The created JavaScript apiView diff is unexpected because there are are lots of diff not shown in apiview. You can find the details by comparing [ApiView link](https://apiviewstaging.azurewebsites.net/Assemblies/Review/c449795588e14cbea3384ba49c3c6fd1?revisionId=660ffe0054dd4196826e8f4ec9f22705&diffRevisionId=5f2a2b01c8d44145af6a911b79225a97&doc=False&diffOnly=False) and [Github PR diff](https://apiviewstaging.azurewebsites.net/Assemblies/Review/c449795588e14cbea3384ba49c3c6fd1?revisionId=660ffe0054dd4196826e8f4ec9f22705&diffRevisionId=5f2a2b01c8d44145af6a911b79225a97&doc=False&diffOnly=False)

**Comment by maririos** [comment]
@praveenkuttappan Is this still an issue?

**Comment by praveenkuttappan** [comment]
I am not sure what's the issue here. I see only two export lines in generated API review file but this package has lot of other lines in API extracted md file. API extractor library is the one generate document model to create API review.

@jeremymeng @joheredi  Can you please let us know if this is some issue in APIView extractor which is not generating all public surface info for `@azure-rest/purview-administration`

Here is the api-extractor MD file: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/purview/purview-administration-rest/review/purview-administration.api.md

Corresponding API view file I generated on staging: https://apiviewstaging.azurewebsites.net/Assemblies/Review/ad1f02281c3d4b4ab50bc441dfe4d6eb

**Comment by jeremymeng** [comment]
@praveenkuttappan where can we find code relevant to use api extractor library to generate document model?  When I build locally, I see expected api.json generated under ./temp folder.

**Comment by maririos** [comment]
@jeremymeng  is this still a thing?

**Comment by maririos** [comment]
Closing issue as we don't have enough information to follow up on it
