### ISSUE TITLE
Don't assign data plane API reviewers to management plane PRs in azure-rest-api-specs

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3494]
The automation to add reviewers to PRs in azure-rest-api-specs should choose reviewers based on whether the PR is for management plane or data plane.

The automation added me as an reviewer on this PR

https://github.com/Azure/azure-rest-api-specs-pr/pull/7656

but that is for a management plane API.  I think the data plane API reviewers should only be auto-assigned to review data plane PRs.

**Comment by mikekistler** [comment]
Agreed that I mixed up assignees and reviewers in the description -- now fixed.

If you believe GitHub is causing this problem, please escalate and link any issue here.

**Comment by weshaggard** [comment]
OK I think I finally solved this mystery. 

![image](https://user-images.githubusercontent.com/9010698/176957224-3782f626-b74a-4d3a-b9b4-8b026f899db6.png)

Originally this PR was targeting main and that diff was a lot larger and did have some changes that matched the pattern `/specification/*/data-plane/ @Azure/api-stewardship-board` which is why the api-stewardship-board was added as a reviewer. This should be an exceptional case so I think we are good on this front. Please reopen if you find other cases we cannot explain.
