### ISSUE TITLE
De-dup SDK review process documentation

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3545]
This is requirement assoicated with the SDK release documentaiton epic - https://github.com/Azure/azure-sdk-tools/issues/5618. 

Currently, there are 2 pages with information about how the review process:
- Guidelines => https://azure.github.io/azure-sdk/policies_reviewprocess.html
- Used for scheduler tool => https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/667/Azure-SDK-Archboard-Review

Information is not consistent between them, and we shouldn't maintain this information in 2 places. The goal of this issue is to seek which strategy we should follow for which document, which structure, which information should be preserve.

**Comment by maririos** [comment]
Will this decision be affected by the docs effort that @ccbarragan is driving?

**Comment by ronniegeraghty** [comment]
I there a reason the Review Policies need to be external facing. If so, I would say we stick with the github.io page and try to update the format of the information there to make it more readable. If there is no reason for the Review Policies to be external facing, then I would say let's stick with the ADO wiki and update the information there.

**Comment by ladonnaq** [comment]
I am not sure why the review policies are external.  As far as I know only internal service partners are engineering team are engaging with the Arch Board for SDK reviews, naming, introduction meetings, etc.  @kyle-patterson - Is there a reason why the specifics regarding these type of meeting should be external?  I can understand why the guidelines are external and should remain in GitHub.

**Comment by kyle-patterson** [comment]
The review process documentation is published externally so that external customers know how to engage with the architecture board if necessary - such as in the case of preparing extensive changes or fixes to our open-source libraries, which might require input or guidance from the architecture board (since these are changes to 1p libraries). In practice, at some point we ended up with internal and public documentation that diverged. 

I think a more pointed question is who owns and who maintains the process documentation - if we believe the process should be owned by the arch board and maintained by the helpdesk, for example, then we should keep the documentation in the GH repo for source control and PR approval by the architects (there is no APIView feature for this, nor to my knowledge support in wikis for this). In this case, I would prefer we correct the github.io experience (maybe related to the docs effort, but I'm not sure) and keep a central location with our general and language guidelines. In this regard, it's less about public vs internal, and more about source control and review... (additionally, I suspect if process navigation is an issue, so is guidelines navigation? In which case we'd need to address usability anyways).

**Comment by ladonnaq** [comment]
@maririos @ccbarragan I created a epic to track all SDK release documentation that is associated with the release planner SDK release milestone.  I added this issue as a todo in that epic.

**Comment by maririos** [comment]
@ronniegeraghty  new website structure is ready. The goal is not to duplicate information across pages.
AS the guidelines already include information about the meetings and stuff, what I recommend is to add in Eng hub links to that and steps on how to use the Scheduler tool. 
But up to you.
The link to the new place is: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-review
Contribution guidelines: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms

**Comment by ronniegeraghty** [comment]
Closing out as I believe we consolidated on Eng Hub for Partner facing docs on the Arch Board.
