### ISSUE TITLE
Change sub service "default" to "None" or "N/A"

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3672]
The word "Default" is confusing. This should be changed to "None" or "N/A"

When this happens the issue that is created should not contain the word "None" or "N/A" but should be omitted.

**Comment by JonathanCrd** [comment]
Thanks for the feedback, this issue has been resolved in:
- https://github.com/Azure/azure-sdk-tools/issues/3556

Note: The change has not been deployed to production yet.

Regarding the GitHub issue containing the word "None", this would not be a problem since the subservice is not specified on it. 

@markweitzel  do you expect to find the Subservice name on the GItHub issue too? If so, I can create a new issue to keep track of this.
