### ISSUE TITLE
There is no way to see the GitHub Issue for SDK Reviews on the app

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#3701]
A GitHub issue is being created every time a new SDK Review is scheduled, but the link to this issue is nowhere to be found on the app, only in the email.

**Comment by maririos** [comment]
What about informational?

**Comment by ladonnaq** [comment]
The Azure Devops work item has a field for the SDK review.  I would like that field updated to track the SDK review.  We could update the product dataverse table and then when the dataverse table syncs to the Azure Devops work item, the field would be updated.  We can also add a field similar to the Info Meeting State which is used to identify if a product has completed informational meeting (for specific scenarios they are required to do this before they create a release plan).

**Comment by maririos** [comment]
This issue is specific to the Scheduler tool. Currently only API Reviews is showing a link.
i.e. 
![image](https://user-images.githubusercontent.com/9868623/202042273-fa87c2ea-deb5-4ac7-a6f5-9424c702b952.png)

Informational doesn't have a GH issue, but aybe we can put the ADO item link here?
SDK needs the link too.

@ladonnaq  as for updating the ADO item with the status of the meetings, I totally agree. Issue https://github.com/Azure/azure-sdk-tools/issues/4681 is a great example for that for Informational.
Could you open issues for API Review and SDK Review where we can see the specific name of the fields, the properties, and the desired behavior?

**Comment by maririos** [comment]
Link included in the list but it is missing adding the GH logo.


![Image](https://user-images.githubusercontent.com/9868623/208787412-403b6ca4-97ee-4c65-bdf1-2225a70f0741.png)

Also included on the Edit view (same as API Review meeting):


![Image](https://user-images.githubusercontent.com/9868623/208787470-f250bde7-ce67-4732-999f-c17ac1726c5d.png)

**Comment by maririos** [comment]
GH logo added
