### ISSUE TITLE
Remove "Run static analysis" and always run static analysis

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-tools#3724]
Due to https://github.com/Azure/azure-sdk-tools/issues/3712, I am trying to create a manual review without static analysis, but unchecking the box at creation time doesn't work.

![image](https://user-images.githubusercontent.com/31998003/180315240-51c4e2b5-94d4-42ca-88c5-71be26ef6ca7.png)

APIView created that it is still running the linter: https://apiview.dev/Assemblies/Review/f654d0b58676400a9fe225b5df013d73

**Comment by tjprescott** [comment]
@praveenkuttappan how does that checkbox affect the invocation of the APIView plugin?  To skip static checking on pylint, you need to run it with `--skip-pylint`.

**Comment by JonathanGiles** [comment]
Just to invade here from a Java perspective - this checkbox has always bothered me because it doesn't do anything in Java - we will always run diagnostics, because, why not? I wish we had a simpler 'create review' dialog that wasn't as confusing (the number of times I've seen people click the 'Java' text at the bottom thinking that enabled them to create a Java review is....embarrassingly large).

**Comment by praveenkuttappan** [comment]
I will remove this checkbox and make run analysis always for al languages. @JonathanGiles I will check if I can simplify this. But languages like JS and C++ benefit from these instructions to run pre steps required to create artifact unlike Python, Java and .Net.

**Comment by JonathanGiles** [comment]
@praveenkuttappan I understand the need to explain the pre-steps. I've always wondered if we should have a separate 'Help' page linked to from the top-nav bar that provides this help (then the upload dialog can just have a 'Need Help?' link on it instead)

**Comment by praveenkuttappan** [comment]
This was already done as part of recent change to support CADL language and create review page was modified as well.
