### ISSUE TITLE
ApiView Automation Option for Azure ADO repositories

### ISSUE THREAD

**Issue by viniciusl-msft** [Azure/azure-sdk-tools#3761]
Azure Communication Services Calling SDK has an Azure ADO workflow for development and release, so it doesn't get advantage of the ApiView automation options on the mono repo on github.

This request is to have a way of automate the ApiView generation, without having to upload an artifact on the website. It can be either:
1. A rest api
2. Command line tool
3. Azure Pipeline Step Template

**Comment by DominikMe** [comment]
@JamesBurnside @alkwa-msft 
The Azure Communication Services Web UI team also works outside of the mono-repos on [Github](https://github.com/Azure/communication-ui-library/actions) and would benefit from a better integration with ApiView. Their CI uses Github Actions and Partner Release Pipelines, so let me add 

4. Github Action :-)

**Comment by viniciusl-msft** [comment]
Hi, any progress/feedback here?

**Comment by kurtzeborn** [comment]
We already have a rest api though it's not documented really well because it's not the way pretty much all other partners use ApiView.  If you really want to call the REST API, you can work with praveen to get pointers to the code so you can see what's supported.  You can upload packages through the REST API as well.

We really only support the usage of these tools for code/projects/services in our shared engineering system.  Like I said, ApiView already has REST apis that your pipelines can call, but you'll have to do the work to call those REST apis yourself.
