### ISSUE TITLE
Improve display of JavaDoc reference text in APIView

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-tools#3769]
There are two issues with the APIView rendering of JavaDoc:

* Bad indentation and odd newlines appearing (although this might have been fixed recently, but we should validate this).
* We should convert some HTML escape characters back into the characters they represent, to make the readability simpler.

Here's a screenshot from APIView marked up with the issues highlighted:

![image](https://user-images.githubusercontent.com/1427840/181379389-d0fd467c-7f08-4939-a254-8830d3efb927.png)

**Comment by cmcd22** [comment]
I'll take care of this issue @JonathanGiles

**Comment by cmcd22** [comment]
@JonathanGiles could I please just some some clarification concerning the reference text indentation?
Are you wanting the reference indentation to match up with the nesting of the classes/methods? Or are you wanting all text at the same indentation? Because removing the indent & unindent methods gives consistent indentation throughout. I've posted a review in APIView that illustrates the look with no text indentation if you'd like to look and let me know if it's what you're after or not. Cheers

**Comment by JonathanGiles** [comment]
The indentation should align with the method indentation.
