### ISSUE TITLE
Add a comment on GH Issue when there is an update to the meeting from the scheduler app

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3990]
i.e. if the user re-scheduler the meeting, or if they upload content, we should add a comment on the GH issue so other people can know about that too

**Comment by maririos** [comment]
First we need to look into the use cases, then we will know how to proceed

**Comment by JonathanCrd** [comment]
These are all of the different use cases for each type of meeting that I came up with.

Feel free to edit this table to add more. We can start filling out the expected behavior too.

App | Use case| Expected behavior on the GitHub Issue
-- | -- | --
API Review | Create new meeting   in existing issue |  
  | Change the meeting   date |  
  | Update the meeting   description |  
  | Add or delete   attendees |  
  | Add API PR number |  
  | Update or delete   API PR number |  
  | Add, update or   remove core concepts link |  
  | Add, update or   remove API Documentation link |  
  | Add, update or   remove Hero Scenarios link |  
SDK Review | Change the meeting   date |  
  | Update meeting   description |  
  | Add or delete   attendees |  
  | Add, update or   remove Hero Scenarios link |  
  | Add, update or   remove Arch Diagram link |  
  | Add, update or   remove Core Concepts link |  
  | Add a new API View   Link |  
  | Remove an API View   Link |  
Informational   Meeting | Change the meeting   date |  
  | Update description |  
  | Add or delete   attendees |  
  | Add, update or   remove Arch Diagram link |  
  | Add, update or   remove Hero Scenarios link |  
  | Add, update or   remove Core Concepts link |

**Comment by maririos** [comment]
I updated the table with some ideas. The same applies for other meeting types.
What I am thinking is that any time something changes (that is not attendees) we can comment on the issue with something like:
```
The following meeting information has been updated by <user>: <list of properties updated. i.e. Date | PR link | Core Concepts |>

-- Here provide all the data again, same as original GH comment but with the updated fields.
```

This way we have one template that works for every update and the reviewers only need to look at the latest comment in order to get the latest information.

@JonathanCrd  What do you think?

**Comment by JonathanCrd** [comment]
I like that approach, so the admins and reviewers will find all of the info in the last bot comment 👍 

I still have a question regarding re-using existing GH Issues. For this particular case, I believe we will need a new template, something like:

```
A new [API | SDK] review has been scheduled by <user name> under this issue:

Date | PR Link | etc
...
```

And I think we will have to re-open the issue too, in case it has been closed already.

**Comment by maririos** [comment]
I will prefer to avoid adding new templates. What we can do, is add a new line to the current template we have. 

For example:
```
New <meeting type> meeting has been requested. ->this is the addition

Service Name: AAD Access Reviews - Tests
Review Created By: Mariana Rios Flores
Review Date: 10/4/2022 10:00 PM
PR:
Hero Scenarios Link: Not Provided
Core Concepts Doc Link: Not Provided

Description:

Detailed meeting information and documents provided can be accessed here...
```

**Comment by maririos** [comment]
> And I think we will have to re-open the issue too, in case it has been closed already.

Which issue are you talking about?

**Comment by JonathanCrd** [comment]
> Which issue are you talking about?

None in particular, I'm talking about the case in which a user chooses to reuse an existing issue, but that existing issue has been closed.

**Comment by maririos** [comment]
Ohhh I follow. Hmm yeah you are right. If they provided a GH issue that was closed, then we will need to reopen.

**Comment by JonathanCrd** [comment]
This is what has to be done for this:

**When editting a meeting**
- [ ] Add new template for GH Update Comments
- [ ] Create a new flow to post a comment on a GitHub issue (or see if the existing cancel meeting flow could be reuse)
- [ ] Add new step when editting a meeting to call that flow

**When creating a new meeting reusing an existing issue**
- [ ] Modify the current template for GitHub Issue description with @maririos's suggestions
- [ ] Adapt the GitHub Comment flow created to use that template when reusing an existing GitHub Issue
  - [ ] If the issue has been closed, re-open it again

**Comment by JonathanCrd** [comment]
Templates have been modified in Prod. This is done :)
