### ISSUE TITLE
Hang analysis diagnostics

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#4087]
If an agent VM times out, can we upload (to artifacts) information about the state of the machine. Perhaps: screenshots, list of running processes, dumps, etc. 

Requested by @RickWinter for C++ tests

**Comment by kurtzeborn** [comment]
Screenshots are not really an option since our pipelines run headless.  Also, as Ben says, we don't really have a way to run a "cleanup" task when a pipeline is being canceled or is timing out.  The best we could think of is to schedule a task at the beginning of the pipeline run to kick off 1 minute before timeout maybe?  It feels janky.  Unless we have a clear plan for this, it feels like we could put a lot of time into this without great results.  It's a good suggestion, but the nature of DevOps pipelines make this a lot more complicated that it is when UI based apps (like Office) do this in their builds and tests.
