### ISSUE TITLE
A meeting was scheduled at a wrong time

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4326]
A user located in India created a meeting, and for some reason the Outlook event for that review was scheduled at 9:30 PM Pacific time. The tracking github issue had written `9:30 PM PT` too which is wrong.

**Comment by JonathanCrd** [comment]
I spotted several problems that need to be addressed regarding this issue:

- [x] The time of the Outlook Event is incorrect
        FIXED: Since we were using Local Time at the start, we don't need to convert or check the status of the toggle again. Removing that from the Start/End build section worked.

- [x] GitHub seems to use the Local Time Instead of PT
        FIXED: The EmailParams were using the _dateSelection as it was, so that's gonnna be always in local time. To fix this, I added a new var named _dateSelectionPT, that is going to have the PT time always. 

- [x] Minutes does not show in the Calendar
       FIXED: For this, I had to change the Calendar component to not reuse the minutes specified in the Schedule, but instead also add the TimeOffset to get the minutes to display.
   - [ ] To do: Update the calendar component in all apps.

- [ ] Real availability does not match the spots shown in the Calendar when switching between PT and User's local time.

**Comment by JonathanCrd** [comment]
For the last problem, this seems to be something that has been there even before making any changes.

**Comment by JonathanCrd** [comment]
@praveenkuttappan do you know if your changes regarding Daylight savings time fixed the issue of weird time slots when switching  between time zones?

**Comment by maririos** [comment]
@JonathanCrd can you create the new issue for the remaining work here?
