### ISSUE TITLE
[Release Planner New Issue] Feedback on Beta V1 Intake Questionnaire

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#4438]
From: Justin Bettencourt <[jbettencourt@microsoft.com](mailto:jbettencourt@microsoft.com)> 
Sent: Friday, September 30, 2022 5:05 AM

Subject: RE: [Onboarding] PMs - Dev Leads sync
![image](https://user-images.githubusercontent.com/18413981/196135215-fd730afd-8283-40a2-8a71-67e37746d84f.png)

**Comment by ladonnaq** [comment]
Here are some additional updates to the UI. 

The title is not correct.  The UI prototype never had the title.  We only want 1 ADO work item, which is used to track the lifecycle of the product (Private Preview, Public Preview, GA).  We should start having a UI playback before new versions are released to production. 


![Image](https://user-images.githubusercontent.com/67656762/198112762-395426cd-2a0a-4d2e-82fc-43134b29954f.png)

Please change the title.   See below. 

![Image](https://user-images.githubusercontent.com/67656762/198112555-ae31b20c-5d84-481b-bc30-c8696b84ef5c.png)

**Comment by ladonnaq** [comment]
@joshfree This questionnaire is for an APEX (previously known as PLR).  We keep one Azure Devops onboard work item for a product in the release project.  We only want one ADO work item which will track the lifecycle of the product (Private Preview, Public Preview, and GA).  When the tool supports ALL release plans, then we will not need the questionnaire to be separate.  Service partners will create the release plans based on the use case (i.e. new service with launch of the initial offering).  Until then we have to keep the questionnaire separate so that we can onboard new products via the tool instead of the old survey and power automate (which does not automatically retrieve the lifecycle and other information from Service Tree and Cloud Lifecycle).  So some of the changes you mentioned related to "text" should can't be updated now but can be updated later.

**Comment by joshfree** [comment]
> @joshfree This questionnaire is for an APEX (previously known as PLR). We keep one Azure Devops onboard work item for a 

I think you meant to tag @josefree here

**Comment by josefree** [comment]
confirm being solved
