### ISSUE TITLE
Allow GitHub Groups in CODEOWNERS

### ISSUE THREAD

**Issue by needuv** [Azure/azure-sdk-tools#4487]
Currently, the [CODEOWNERS in `azure-sdk-for-python`](https://github.com/Azure/azure-sdk-for-python/blob/main/.github/CODEOWNERS) does not allow GitHub groups to be listed as owners for code paths. 

The [AzureML SDK](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/ml/azure-ai-ml) was recently onboarded to `azure-sdk-for-python`, and we have a large organization with at least 6 or 7 teams (each having at least 5-6 developers) owning/contributing to distinct areas of the SDK. We need to be able to list a single owning team for a particular code path rather than having to list out individual owners, as it is hard to maintain `CODEOWNERS` currently if people leave or if there are re-orgs. It could also benefit other orgs with maintaining ownership of their SDKs, as they only have to worry about team membership rather than updating the `CODEOWNERS` file itself.

Based on a conversation with @scbedd, it should be possible with a change in this file to query for team membership: https://github.com/Azure/azure-sdk-tools/blob/5cf9572442e9a52d011e7789c3cb74ff91cded20/tools/notification-configuration/github-codeowner-subscriber/Program.cs#L132, but it would be great to get some eyes on this and make the change.

**Comment by weshaggard** [comment]
@needuv can you give more details about what team you would like to use in the code owners file? Even if we were to fix this for the pipeline notifications there would be other things that would be broken. For example, to be able to use a team in a codeowners file that team must also have write permissions (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) to the repo which is generally not the case for most teams. So we wouldn't be able to simply use any random team there would need to be other work necessary in order to be able to use that team.

**Comment by konrad-jamrozik** [comment]
@weshaggard  I have some questions regarding our implementation of our relevant feature.

Q1: I understand the GitHub natively supports teams in CODEOWNERS file, but with the write-access-required limitation as mentioned by you. From the link you shared:

```
# Teams can be specified as code owners as well. Teams should
# be identified in the format @org/team-name. Teams must have
# explicit write access to the repository. In this example,
# the octocats team in the octo-org organization owns all .txt files.
*.txt @octo-org/octocats
```

However, our custom handling of CODEOWNERS is, to my understanding, required for automatic build failure notifications via Azure DevOps notifications system, of the build pipelines that are automatically deduced and correlated to the relevant file paths in the CODEOWNERS file. Thus, if we would to extend our custom CODEOWNERS parser to handle teams, we wouldn't have to worry about the teams having explicit write access to the repo - this is a GitHub limitation, not Azure DevOps. We should be able to hook these teams in ADO notification system, and it should just work. Am I missing something here?

Q2: I was analyzing how our implementation works, and I encountered unexpected behavior; either I am misunderstanding something, or I found a bug. Consider the team [137 python - servicebus - tests](https://dev.azure.com/azure-sdk/internal/_settings/teams?subjectDescriptor=vssgp.Uy0xLTktMTU1MTM3NDI0NS03MjEyMjY4NDEtNDc1NTgxMjYxLTI3MDQxNzIzOTItMzQ2Mzk5NTc2NS0xLTQyMjY0MTU4NTUtMTk1NzMxODk4Mi0yNzQyMTg3ODExLTk4MjQ5MDE5OQ) created [by our automation (
azure-sdk / internal / automation - build-failure-notification-subscriptions)](https://dev.azure.com/azure-sdk/internal/_build?definitionId=679&_a=summary), from [this CODEOWNERS line](https://github.com/Azure/azure-sdk-for-python/blob/6642030e89d05510d6215fab9f740f176271a65f/.github/CODEOWNERS#L263) for the pipeline [python - serivcebus - tests](https://dev.azure.com/azure-sdk/internal/_build?definitionId=137). To my understanding, in [that team's ADO Notifications pane](https://dev.azure.com/azure-sdk/internal/_settings/notifications?teamId=aab6183d-585b-44fe-ae3d-9d25ad6afd58) we should see it is subscribed to build failures, similarly to how it looks for [the "5213 Code owners sync notification" team](https://dev.azure.com/azure-sdk/internal/_settings/notifications?teamId=bd160387-297f-402e-856f-a594530845b7). **But there is no such "A build fails" subscription**.

I also checked it by making REST API calls to ADO:

```
https://dev.azure.com/azure-sdk/_apis/notification/subscriptions?api-version=7.1-preview.1  
https://dev.azure.com/azure-sdk/_apis/notification/subscriptions?targetId=137&api-version=7.1-preview.1
```

per [this ADO REST API doc](https://learn.microsoft.com/en-us/rest/api/azure/devops/notification/subscriptions/list?view=azure-devops-rest-7.1&tabs=HTTP). The returned JSON didn't return any "A build fails" notification subscriptions for the relevant team.

To my understanding, the relevant code that was supposed to create this notification [is here, in `EnsureScheduledBuildFailSubscriptionExists`](https://github.com/Azure/azure-sdk-tools/blob/5cf9572442e9a52d011e7789c3cb74ff91cded20/tools/notification-configuration/notification-creator/NotificationConfigurator.cs#L316-L355).

Based on that code snippet, there should be a subscription with `description` of `A build fails #AutomaticBuildFailureNotification`, but there is none.

This code wasn't recently invoked because it gets invoked only if the ADO teams we generate need to be upserted.

Could you check my thinking and let me know how to interpret what I am seeing?

Q3: if I would like to run our `notification-creator` for testing purposes, to see if the notification teams and subscriptions are created the way I expect them to as explained in Q2, what is the recommended way for me to approach it? One way I can think of is to create a new test dir, with new test.yml, new CODEOWNERS entry for it and then run our relevant tooling pipelines to create the pipeline for the test.yml, and then, the ADO teams and notification subscriptions. But I am unsure in which SDK language repo to do it, and if perhaps we have better approach to runtime testing.

**Comment by konrad-jamrozik** [comment]
I had a chat with @weshaggard. Here are the answers to my questions.

Q1A: basically, we cannot tell people "hey, now you can add a team and it will properly send build failure notifications to all members, but if it doesn't have write permissions, it won't properly add PR reviewers". It needs to work fully to avoid confusion and half-broken features. I elaborated on our discussion further in this issue I just filed: #4859.

Q2A: turns out the subscriptions are there, but I couldn't see them, as I was missing membership in the `Azure SDK Engineering System Administrators` security group.

Q3A: there is no established way of conducting such tests. In this specific case, I need to do whatever it takes to get a runtime execution, e.g. by adjusting the code to run on my own branch or directory, and running it locally. I could deploy the custom code from my own branch, thus bypassing the formal PR review and wait times. I could run the custom code against one of our repos, e.g. `azure-sdk-for-net`, as long as I ensure I won't introduce any lasting bad state, i.e. revert to good state once my experiment is done.

**Comment by konrad-jamrozik** [comment]
Relevant code: [CodeownersEntry.IsGitHubUserAlias](https://github.com/Azure/azure-sdk-tools/blob/ec7fdf88739040b22ecaa92be67ae8472cb4ad48/tools/code-owners-parser/CodeOwnersParser/CodeownersEntry.cs#L158-L169):

```
        /// <summary>
        /// Helper method to check if it is valid github alias.
        /// </summary>
        /// <param name="alias">Alias string.</param>
        /// <returns>True if it is a github alias, Otherwise false.</returns>
        private static bool IsGitHubUserAlias(string alias)
        {
            // We used to call the github users api but we often got 403 returned
            // due to rate limiting. So instead we are approximating the check
            // by check for a slash in the name if there is one then we will consider
            // it to be a team instead of a users. 
            if (alias.Contains('/'))
            {
                return false;
            }
            return true;
        }
```

**Comment by JimSuplizio** [comment]
The implementation of this was not completely straightforward. The classic github token cannot have `org->membership:read-only` permissions which means that only a fine-grained token will work since it can be granted those permissions. Further, the user that generated the token needs to be a member of Azure in order to query Azure team membership. As such the following restrictions apply:
1. All teams must be under the Azure org. As mentioned above, this is necessary in order to be able to query team membership.
2. As per [GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), all teams in CODEOWNERS files must have write permission for the repository even if the individuals in that team already have write permission. Further, for our purposes, all teams with write permissions should be [child teams under azure-sdk-write](https://github.com/orgs/Azure/teams/azure-sdk-write/teams), meaning their team's write membership is inherited from that team.

The implementation was in two parts. 
1. The first part is a tool called [github-team-user-store](https://github.com/Azure/azure-sdk-tools/tree/main/tools/github-team-user-store#github-team-user-store). This tool runs daily as part of the internal [pipeline owners extraction](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5112&_a=summary) pipeline. This tool gathers all team/user data for child teams under azure-sdk-write and stores them in blob storage. It does this every 24 hours right now.
2. CodeOwnersParser, which is the tool used by various pieces of automation, will automatically substitute the team members when it encounters a team while parsing a CODEOWNERS file (provided the above restrictions are met). It'll pull the team/user data from blob storage to do this.
