### ISSUE TITLE
Collect metrics from Azure SDK Release Planner Beta 2 to determine lead times for Cadl + DPG

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4536]
Lead times were requested by the service partners during feedback sessions pertaining to the Azure SDK team's engagement processes (specifically onboard questionnaire through API review - ARM and API Stewardship Board).   

We need to keep track of the lead times for tasks and milestones so we can provide reasonable lead times in the release plans.

**Comment by josefree** [comment]
bring to triage

**Comment by josefree** [comment]
use this to track metrics requirements

**Comment by live1206** [comment]
Since the creation time and starting time of `Base Step` are not aligning right now. We need to manually add a column to record the starting time of steps. The same goes for `Base Workflow` and `SDK Release Workflow Epics`.
@honghr will help to implement this while operating with release plans, milestones and tasks in Canvas App.

**Comment by ladonnaq** [comment]
Closing this issue for now because tracking the milestones will not reflect the real lead time as far as work effort.  Let's use the work that @maririos is doing for the TypeSpec dashboard to see if any of this data would help to get more accurate lead times.
