### ISSUE TITLE
Notification Design

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#4593]
Currently, PowerApps solution does not have any notification set up.  We should define some events for notification.  Some in my mind
- When product launch date is deferred. 
- When primary PM,  milestone owner of a release plan has been changed
- when SDK release date is closing, say within 8 working days
- when SDK launch date arrives, but SDK release plan is not complete.
- When SDK release plan is complete
- etc.

Besides defining notification events, we also need to define notification level, and who to notify.

**Comment by josefree** [comment]
there should be a central notification framework for Release Planner. bring this requirement to engineer triage

**Comment by live1206** [comment]
Suggestion from @ccbarragan:
For app-level error notifications, I would recommend using a message bar. This is a common thing we see in lots of Microsoft experiences. There’s a good write-up here: [Message bar (coherence-portal.azurewebsites.net)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcoherence-portal.azurewebsites.net%2FControls%2FmessageBar%23Usage%26Placement&data=05%7C01%7Chuwe%40microsoft.com%7C292a59702b6747e9c81108db09633bbe%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638114094105149678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yAa94jg2UNevFwK2Tz2k5Fj%2BGCW7Kl2LqoSv1y5u5OA%3D&reserved=0)

The takeaway is that we should make sure that notifications appear below the most relevant section that the user is interacting with. Because the built-in Power Apps notifications appear alllll the way to the top, far away from the area that I’m actually working in (and they disappear without giving me the option to have them persist), we will continue to get similar feedback.

Here’s an example on how this could look in Power Apps. The message bar appears at the top of the view and pushes down the main content to maintain spacing. Note that there are several different kinds of notifications that work best in different situations – we have message bars like this one, inline validation for input fields in a form, toast notifications, notifications in a side panel vs. a pop-up dialog. [This page](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcoherence-portal.azurewebsites.net%2FGuidelines%2FNotificationUIBasics%23Components%26How%2520to%2520use%2520this%2520page&data=05%7C01%7Chuwe%40microsoft.com%7C292a59702b6747e9c81108db09633bbe%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638114094105149678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=h7sCoGwJOlCJexpn6r3GUMnzvoAZmj%2B8sMw7G1esNcQ%3D&reserved=0) has some really great guidance we can built on.
![image](https://user-images.githubusercontent.com/5196139/217485207-632af912-291e-4b0a-b5cc-74235001a926.png)

**Comment by maririos** [comment]
This will be covered in https://github.com/Azure/azure-sdk-tools/issues/5631
