### ISSUE TITLE
How to identify data-plane only service from Service Tree

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#4597]
A service could only have data-plane API without manage-plane API. 
Then this kind of services are missing in our data importing from service tree.

As we use ARMNamespace to identify management-plane API, do you know how we identify data-plane API in service tree data?

**Comment by ladonnaq** [comment]
@live1206 Any service deployed via ARM, would typically have management plane API in the azure-rest-api-specs repo.  There are products that are only in scope for data plane APIs because there are no changes to the existing management plane API.  For example, most of the Cognitive Services products require new data plane APIs but no changes to management plane API.  

Do know of an example of this scenario in the API specs repo?  

- I think that if a service is a standalone SaaS solution, not deployed via ARM, then it would fall into this scenario.  There are services that have products in scope for APEX that will have to go through onboarding with us. I review these scenarios with Peter and Mayuri to decide if they data plane APIs are Azure APIs and belong in our repositories and our SDKs.  Most of these do have services mapped to the product but there would be no ARM namespace because they are not deployed via ARM.  

- Acquisitions like PlayFab fall into this scenario because they were migrating from another cloud to Azure. So service is not deployed to ARM but they wanted to start working on the data plane APIs. So they engaged our team for help with the data plane APIs.  This is likely why no service shows up for Azure PlayFab Offering in service tree yet.  

![Image](https://user-images.githubusercontent.com/67656762/199548651-61f096de-2e13-4f6b-8f00-56dd247af623.png)

**Comment by live1206** [comment]
@ladonnaq Thanks for the explanation, I have got a better understanding of the context now.
Because I found there are around 20,000 different services in service tree Kusto cluster.
Right now, we use `ARM namespace` to identify the valid services, the number reduced to around 300.
Given the service is not deployed via ARM, how can we identify it is a valid service to us?

**Comment by maririos** [comment]
@ladonnaq are you suggesting there is no other way to filter information but to bring all 20.000 services?

**Comment by maririos** [comment]
An option for now could be to provide the option for the user to give the tool the service tree identifier. The release planner will fetch the information and propulate the rest (product, etc).

**Comment by ladonnaq** [comment]
That is a good idea.  We could have a checkbox "I cannot find my service".  If the user checks the box then another field appears and we ask for the service tree identifier.  We should explain how they can find this information using service tree. 
Here is the example using Azure Dedicated HSM.  The service tree identifier can be found by looking at the product service tree record and then look at the service mapped to it.   

![image](https://user-images.githubusercontent.com/67656762/202314400-683226e1-c864-4a8f-a54a-8ce7f846e10c.png)

 We also are going to find the scenario where there is not a product yet for new services.   How do we handle that once they get by the service drop-down box.    Here is an example that came our way earlier today.  This is a new service with no product yet.  They are defining their initial offering which is an SDK.  

![image](https://user-images.githubusercontent.com/67656762/202314107-b7c6da81-a868-4840-93a8-445944c44316.png)

**Comment by maririos** [comment]
> That is a good idea. We could have a checkbox "I cannot find my service". If the user checks the box then another field appears and we ask for the service tree identifier. We should explain how they can find this information using service tree.
Here is the example using Azure Dedicated HSM. The service tree identifier can be found by looking at the product service tree record and then look at the service mapped to it.

I like it. @live1206 what do you think?

**Comment by maririos** [comment]
> We also are going to find the scenario where there is not a product yet for new services

@ladonnaq what are the implications for our team if there is no product? Are they engaging with us too early? can they actually start interacting with us even though this is not defined? how common is this scenario?

**Comment by ladonnaq** [comment]
We want to offer API design guidance, so we want services to engage with us earlier vs later.  This service is not the most common type we see because it is an SDK - there does not seem to be anything deployed to ARM (no ARM namespace).   So it would be data plane only.  For this team we would want to introduce them to Cadl, have the API Stewardship Board meet with them for an intro to the service, discuss their API design, and even perhaps assign a mentor from the Stewardship Board.

**Comment by live1206** [comment]
@maririos @ladonnaq 
I think this is a good idea as well! 
We have the mapping of services and products in place, and products as well. What we are missing here is only the services.
It's not an issue to take all 20,000 services to dataverse, but it would be a long list for user to choose from.
If the service is not launched on Azure, we can let the user to input the service tree id, then we fetch the service data from service tree. I think this will not cause heavy traffic to service tree since it doesn't seem to be a common user case.

**Comment by maririos** [comment]
Let's try this approach then in the Release Planner app. If we see that more than 10% of the services are hitting this route, we can revisit the overall strategy.

Once we have more data we can follow the same strategy in the Scheduler app.

**Comment by live1206** [comment]
@maririos @ladonnaq I found an issue with this approach, if we let the user to input the service id and pull this service from service tree manually. We do not have a proper way to sync and update this manually input service, because the kusto query we have do not contain this service. I found another filter condition(the service should public), with this in place, the service number reduces to 4,000. The user is going to use search box to filter out the service from 300+ anyway, is it acceptable to sync all these 4,000 services from service tree?

**Comment by maririos** [comment]
@live1206 does this mean that we first sync the service Tree data to a Kusto instance, and then from there we sync to Dataverse?

**Comment by live1206** [comment]
> @live1206 does this mean that we first sync the service Tree data to a Kusto instance, and then from there we sync to Dataverse?

We query from service tree Kusto cluster and sync data directly to dataverse.

**Comment by live1206** [comment]
Added all public services.
