### ISSUE TITLE
Customer reported: Azure Cloud HSM not showing up in Service dropdown box 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4625]
Customer reported Azure Cloud HSM not showing up in Service dropdown menu of Release Planner Beta 1. 

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/67656762/200054461-91b20182-f93a-421a-8596-ce9e886e57d5.png">

[CLC link](https://vnext.s360.msftcloudes.com/cloudLifecycle/products?blade=stage:1~program:All~kpiowner:All~Domains:All~_loc:cloudLifecycle&def=&peopleBasedNodes=&global=8:7625d188-2d30-4520-ae76-7f2f17bcbc07&selectedTab=Mandated&actionItemId=)
[Service ServiceTree link](https://microsoftservicetree.com/services/97d8210f-d1ef-4614-91b2-d32471e13a08)
[Product ServiceTree link](https://microsoftservicetree.com/products/7625d188-2d30-4520-ae76-7f2f17bcbc07)

**Comment by ladonnaq** [comment]
Hello @live1206 - This has been sitting here for way too long.  I met with the service partner and provided all the information they need for onboarding.  I told them once the bug was resolved; I would go ahead and complete the intake questionnaire so that the work item will be created.  We need to have a queue for user found bugs and start having the service partners create the bug issues from the release planner app.  I will open a separate GitHub issue for that feature.

**Comment by live1206** [comment]
@maririos @ladonnaq 
I think this is a good idea as well! 
We have the mapping of services and products in place, and products as well. What we are missing here is only the services.
It's not an issue to take all 20,000 services to dataverse, but it would be a long list for user to choose from.
If the service is not launched on Azure, we can let the user to input the service tree id, then we fetch the service data from service tree. I think this will not cause heavy traffic to service tree since it doesn't seem to be a common user case.

**Comment by live1206** [comment]
@ladonnaq  The missing service can be selected in Prod now:
![image](https://user-images.githubusercontent.com/5196139/203680665-7046251f-7d1e-42d8-8648-28cb56b584d2.png)
