### ISSUE TITLE
Address APIView swagger feedback

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4647]
Issues track potential issues or changes requested in APIView for Swagger these may include.
- Ensure parser creates token consistently across different revisions.
![SwaggerIssue1](https://user-images.githubusercontent.com/31145988/200407384-51642c43-28d3-4f50-bc2f-564f870debf1.png)
https://apiview.dev/Assemblies/Review/878ea27771a045aca67f2bd6e84ca0b6?diffRevisionId=34129f25c84643b5877387ad1742c2f3&diffOnly=False&revisionId=82dd9ea5438c43159065f081b71beb3e&doc=False
- Update parser to support subsection heading under Definitions and Parameters. (Requires more discussion)
- Ensure there are no errors in swagger logic. see `Definitions -> EvaluationContract` in https://apiview.dev/Assemblies/Review/878ea27771a045aca67f2bd6e84ca0b6?diffRevisionId=34129f25c84643b5877387ad1742c2f3&diffOnly=False&revisionId=82dd9ea5438c43159065f081b71beb3e&doc=False

**Comment by chidozieononiwu** [comment]
Looking into this there is definitely an issue with the swagger parser which results in parsing 

> "EvaluationContract": {
        "description": "A counterfactual evaluation.",
        "required": [
          "endTime",
          "name",
          "startTime"
        ],
        "type": "object",
        "properties": {
          "name": {
            "description": "The name of the evaluation.",
            "maxLength": 256,
            "type": "string"
          },
          "startTime": {
            "format": "date-time",
            "description": "The start time of the evaluation.",
            "type": "string"
          },
          "endTime": {
            "format": "date-time",
            "description": "The end time of the evaluation.",
            "type": "string"
          },
          "policies": {
            "description": "Additional learning settings to evaluate.",
            "type": "array",
            "items": {
              "$ref": "#/definitions/PolicyContract"
            }
          },
          "enablePolicyOptimization": {
            "description": "True if the evaluation should explore for a more optimal learning settings.",
            "type": "boolean"
          }
        }
      }
      
to get

> <html>
<body>


Field | Type/Format | Keywords | Description
-- | -- | -- | --
+name | string | required | The name of the evaluation.
+startTime | string/date-time | required | The start time of the evaluation.
+endTime | string/date-time | required | The end time of the evaluation.
+policies | array<PolicyContract> | required | Additional learning settings to evaluate.
+name | string | required | Name of the learning settings.
+arguments | string | required | Arguments of the learning settings.


</body>
</html>

The issue though is on the parser side rather than the rendering side. @ruowan is this one of the bugfixes you tackled recently?

**Comment by ruowan** [comment]
For the first one, the apim_key is different. The new property description was added. And to reduce display content. In parser, if some json object has less properties, the parser will use one line.

**Comment by ruowan** [comment]
I created a PR to fix the third issue https://github.com/Azure/azure-sdk-tools/pull/4794

**Comment by ruowan** [comment]
The PR is been merge. And now our azure-rest-api-spec PR pipeline is using the latest 1.0.4 version. @maririos  Maybe we could close this issue.
