### ISSUE TITLE
highlight for the user that they are running outside of Prod

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#4782]
If a user is using a non-prod instance, we make it obvious they are using a dev, test, ppe, or some other non-prod environment.  We should not rely on version # alone

**Comment by josefree** [comment]
agree. bring this to engineering triage

**Comment by ccbarragan** [comment]
I usually see deployment environments being labeled by URL (for example `https://<environment>.loop.microsoft.com`, where the `<environment>` segment signals the test / pre-prod environment). would be cool if we could follow what folks might already have an established mental model for if possible.

@MrJustinB @josefree Some questions:

1. In what cases would a service partner need to use or access a non-prod environment of Release Planner / Scheduler?
2. Do our users need to know the version # of the app that they're using?

    My assumption here is that knowing the app version number might come in handy for a user when it comes to troubleshooting, but otherwise prominently highlighting it in the app might not be necessary. I'd expect to be able to access it from a Settings page / panel or maybe displayed in an error notification.


Regarding a label - if users will be accessing multiple environments, and if we can't signal this in the URL itself, would be good to highlight in the app itself. I'd advocate first for URLs that map to different deployment environments. But if there's a limitation around that, we could add something to the top nav. Couple options:


| | |
|---|---|
| Append to the app title | ![CleanShot 2022-11-23 at 12 28 58](https://user-images.githubusercontent.com/28902259/203621875-67e02b98-b5da-4c4d-8713-b766c049a047.png)|
| Badge | ![CleanShot 2022-11-23 at 12 30 43](https://user-images.githubusercontent.com/28902259/203622051-9f4ce2f2-6f28-4613-81ae-48ba3c59c5a5.png)|

**Comment by maririos** [comment]
> In what cases would a service partner need to use or access a non-prod environment of Release Planner / Scheduler?

They should only use Prod environment.

This will help more the Azure SDK team when working on new features and asking for feedback which will happen in Pre-oproduction (PPE)

**Comment by maririos** [comment]
> Do our users need to know the version # of the app that they're using?

My assumption here is that knowing the app version number might come in handy for a user when it comes to troubleshooting, but otherwise prominently highlighting it in the app might not be necessary. I'd expect to be able to access it from a Settings page / panel or maybe displayed in an error notification.

Correct. My concern is that if we hide it, and a user run into a problem that was not expected and adds a screenshot, Engineering won't know the version. If we have the version always visible, then the user doesn't have to think about it? 🤷‍♀️

**Comment by ccbarragan** [comment]
>My concern is that if we hide it, and a user run into a problem that was not expected and adds a screenshot, Engineering won't know the version. If we have the version always visible, then the user doesn't have to think about it? 🤷‍♀️

@maririos Valid concern! Can users run different versions of the app? If I have an app instance, and there's a new version deployed, will my instance be automatically be upgraded to the latest version? Trying to understand how we might come into a situation where users would have versions of the app that don't map to the latest.

**Comment by maririos** [comment]
> Can users run different versions of the app?

If you have the app open while there is a deployment, the only way to get latest is to refresh the page, but otherwise all users should have same app version.
The case is that when they report a bug, if it is not critical and we don't need to provide a fix right away, we will include the version in the GH issue and that will help to provide a fix later on.

**Comment by maririos** [comment]
This has been address by including the name of the environment and the version to every view of the apps
