### ISSUE TITLE
duplicated ADO work items are created upon the same product

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#4912]
[Onboard 13836](https://dev.azure.com/azure-sdk/Release/_workitems/edit/13836): SDK Intake - Azure Communications Gateway
[Onboard 13837](https://dev.azure.com/azure-sdk/Release/_workitems/edit/13837): SDK Intake - Azure Communications Gateway

Difference between 1st submission and 2nd submission was - 1st time I chose 'No' for Data Plane scope question, while 2nd time I chose 'Yes'.

**Comment by live1206** [comment]
@josefree 
It seems like [Onboard 13836](https://dev.azure.com/azure-sdk/Release/_workitems/edit/13836) was created in Prod environment, because it is missing label `Release Planner App Test`
![image](https://user-images.githubusercontent.com/5196139/206999675-49174834-5ba1-4e46-a149-ecbf32f4cb74.png)
Verified in Dataverse of Prod as well:
![image](https://user-images.githubusercontent.com/5196139/207000465-04160682-72f4-407a-aa81-72abfc8acc00.png)

[Onboard 13837](https://dev.azure.com/azure-sdk/Release/_workitems/edit/13837) was created in non-Prod environment, it has the bale `Release Planner App Test`
![image](https://user-images.githubusercontent.com/5196139/207000102-be500ec7-c0c0-473f-ad55-c1f02dac2458.png)

**Comment by maririos** [comment]
Does this means that if a Service-Product already has an ADO item with the tag `Release Planner App Test` , but they are going against PROD to create the ADO item, will they get the warning? or PROD environment doesn't look at the issues with the test tag

**Comment by live1206** [comment]
> Does this means that if a Service-Product already has an ADO item with the tag `Release Planner App Test` , but they are going against PROD to create the ADO item, will they get the warning? or PROD environment doesn't look at the issues with the test tag

 Prod, PPE and Dev have separated Dataverse tables, the check is only against the corresponding environment, not across them.
Or to say, the ADO items created in PPE or Dev will not affect the products in Prod.

The bug was raised by @josefree, she created the ADO items in PPE and Prod for the same product, which should end up into different ADO work items.
