### ISSUE TITLE
CADL API review - API review is not generated when emitter has warnings

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5038]
API review file is not generated in output path when emitter throws warnings. This issue only happens on CI machine.  By default warnings are not treated as errors but CI considers warnings as errors.

**Comment by tjprescott** [comment]
@praveenkuttappan and I met and looked into this. The PR-based pipeline for generating token files works even if there are warnings (which is what happens if you run apiview locally too). It's only the manual, url-based pipeline that fails to output if cadl outputs warnings, which means the issue lies in that pipeline.

Notably, the manual pipeline uses Powershell while the PR-pipeline uses CMD, so that might be a source of the discrepancy.

**Comment by praveenkuttappan** [comment]
Fix was included in following PR to find the token file recursively from output path. https://github.com/Azure/azure-sdk-tools/pull/5196
