### ISSUE TITLE
Don't send scheduling emails for non-review blocked days

### ISSUE THREAD

**Issue by kyle-patterson** [Azure/azure-sdk-tools#5049]
@ronniegeraghty and I need the ability to schedule "off days" for days without review - until the ability to schedule or remove individual days is available.

As a workaround, we can schedule under a fake service - product ("Azure SDK - No Session", for example) that does __not__ generate an email to anyone?

**Comment by kyle-patterson** [comment]
This could also be helpful with a fake product "Alternate Timezone") that blocks other service teams from booking, but Ronnie and I could schedule manually (until different times are supported)

**Comment by maririos** [comment]
As a test service you could use the `Release Planner Test Service`. In order to not send emails to everyone, the workaround we have for now is:
- From the Admin app, go to `Event Reviewers`
- Delete the emails you don't want
- From the scheduler app, schedule the meetings
- When done, go back to admin app and add the deleted emails.

Another option is you can send me an email with the dates you want blocked and I will do that.

As you said, this is all temporary until we enable the ability for the admins to block a day

**Comment by maririos** [comment]
> As a workaround, we can schedule under a fake service - product ("Azure SDK - No Session", for example) that does not generate an email to anyone?

Let me look into this. It shouldn't involve too many changes. I will update this issue with the findings

**Comment by maririos** [comment]
Change has been implemented! It will not create a GH issue and it will send the calendar invite to the admin of the meeting and the azdexp team
