### ISSUE TITLE
Make common test resource variables always available

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#505]
A common pattern I've noticed in test-resource.json files is returning common variables out without modification.

Something like:

``` json
    "AZURE_TENANT_ID": {
        "type": "string",
        "value": "[parameters('tenantId')]"
    },
    "AZURE_CLIENT_ID": {
        "type": "string",
        "value": "[parameters('testApplicationId')]"
    },
    "AZURE_CLIENT_SECRET": {
        "type": "string",
        "value": "[parameters('testApplicationSecret')]"
    },
```

I think we should always set the following ones even if the template doesn't define them as output:

`AZURE_TENANT_ID`, `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET`, `AZURE_SUBSCRIPTION_ID`

@danieljurek @heaths

**Comment by heaths** [comment]
The original idea was because they weren't needed by every service. For example, storage doesn't need them if using connection strings. Search doesn't actually need them because it uses an api-key (doesn't even support SPs). It might be worth it to instead remove these variables when not needed. At least for dev machines, it reduces how many have stored secrets stored as environment variables.

**Comment by pakrym** [comment]
Yes, but having them doesn't hurt and most services can use AAD

**Comment by heaths** [comment]
Does this require that all test-resources.json files be modified to rename variables accordingly, or will the `TestEnvironment` fall back to names as-is if requested?

**Comment by pakrym** [comment]
We would need to cleanup `test-resources.json` and remove variables that are not required anymore but this can be done in any point in time because the TestEnvironment would fall back to non-prefixed names.
