### ISSUE TITLE
Provide the flexibility to change default tag in readme for mgmt. SDK release

### ISSUE THREAD

**Issue by lirenhe** [Azure/azure-sdk-tools#5069]
We need to revise design because users do not understand what and why they are supposed to ensure that this step is completed.  We need to offer additional guidance and maybe link to example.  

**Current Implementation in the Release Planner Management Plane SDK Release App** 

In mgmt. SDK, some services shared the same readme file so the default tag would be incorrect to identify the real service for release.
e.g.
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/readme.md

Please provide the flexibility to use another tag for the release.

![image](https://user-images.githubusercontent.com/9100546/210912748-2c28b488-c384-4ea5-9f92-207dfec7a238.png)

**Comment by ladonnaq** [comment]
@praveenkuttappan @maririos Here is the issue that was related to the addition of the option to change the default tag in readme for management SDK releases.  Do we want to use this to address changes to functionality so that it makes sense?  Right now, no one understand what they are supposed to do and why.  We can also open a new issue.  Let me know if you prefer we do that...

**Comment by maririos** [comment]
We can leave this as guidance and investigation for now

**Comment by maririos** [comment]
This applies only if the API Spec is swagger. At this point, we can only check that the tag is ok. 
Eventually we could update it, but for now a check is just enough.

@ladonnaq  Should this still happen in the pre-requisites? or where?

**Comment by maririos** [comment]
This is no longer present in the SDK apps.
Changes made based on https://www.figma.com/file/JzbPB3xPwrjdxJ5SiG7hYD/Design-sync%3A-SDK-readiness?type=whiteboard&node-id=0-1&t=3DS7wrOEmrnoyo9G-0
