### ISSUE TITLE
The mgmt SDK release apps should be centralized place for all information

### ISSUE THREAD

**Issue by lirenhe** [Azure/azure-sdk-tools#5072]
From the apps, we still ask service team to go to release request to provide additional information which   cause people to switch between different places.
We need to have one centralized place for all information. 

![image](https://user-images.githubusercontent.com/9100546/210917249-a1eacdb5-db5e-428e-b624-9f85088ae5b7.png)

**Comment by ladonnaq** [comment]
Closed.  The link has been removed.  This screen and functionality will be modified in the current UI so that it is clearly understood that the SDKs are NOT released until the "requested" monthly train or date (if out of cycle release is approved).  https://github.com/Azure/azure-sdk-tools/issues/6423
