### ISSUE TITLE
Network error when updating date of an Informational meeting

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5074]
Repro steps:
- Create a meeting with service name and product
- Update the meeting date

Error is:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/9868623/211072778-99fc9f78-dddc-445e-b29d-0b09519df1c0.png">

Seems related to the `Product` field as the meeting is correctly updated and the calendar invite reflects the new date, but the `Product` field appears as empty only in the calendar invite. The product is still present in Dataverse

**Comment by JonathanCrd** [comment]
The error is that the ComboBox selected record when editting a meeting does not match the Product schema. Thus, when submitting an update, the patch to the Database fails.

However, for SDK reviews the users are not expected to edit the product information once they have created the meeting. So, the product information was removed from all patch in the Update part of the code, and when editting a meeting the Product record will come from the currently saved table record and not from the combo-box.

This issue has been solved in the SDK Review App, it is still present in the Informational Meeting App.

**Comment by JonathanCrd** [comment]
This same error has been fixed in the Informational App as well.
For this, the feature to change the Product field remains the same.

In order to fix this bug, **I needed to turn off a preview feature that prevents the apps for fetching columns that are not explicity used**. This will have a negative effect on the performance, but, so far I haven't notice a significant change in performance while using the app.

This is the feature that has to be turned off:
![image](https://user-images.githubusercontent.com/17486462/211429403-cd439c69-021c-446d-8eb1-b603629a03aa.png)


Also, the default record for the Product Combo Box does not contain the whole Product record information. We might want to revisit this combo box in the future to improve it.
