### ISSUE TITLE
Update data plane Welcome Screens to look like management plane 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5221]
Crystal will be working on new UI wireframes for the API Readiness and SDK Release apps for data and management plane.  The current data plane welcome screens were found to be very confusing.  The management plane Welcome screens have considered that feedback and have removed the checkboxes. 
Example of management plane UI: 
![image](https://user-images.githubusercontent.com/67656762/214672756-2c6a4e87-33ab-48ee-b752-d1731436e024.png)

Tasks to be done: 

- [x] Update the data plane API Readiness Welcome screen
- [x] Update the data plane SDK release Welcome screen

**Comment by maririos** [comment]
There is another issue https://github.com/Azure/azure-sdk-tools/issues/5128 that questions the quality of the information that we are presenting.
I will say this issue is Urgent and the one that changes the information should be high. @ladonnaq if you disagree, let's consolidate the issues and clarify what we should do

**Comment by zzvswxy** [comment]
DPG SDK Release App done in Dev env

**Comment by honghr** [comment]
Data plane API readiness App is done.

**Comment by live1206** [comment]
@honghr Reopen it since it is not deployed to Prod yet.

**Comment by live1206** [comment]
Change deployed to Prod
![image](https://user-images.githubusercontent.com/5196139/215683877-df8f90e5-4002-402b-9ecb-aed426c478cc.png)
