### ISSUE TITLE
Product Profiles are missing the Name in Prod

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#5228]
There was an error in Production where the meeting name was empty. 
This was caused due to an empty `Name` on the Product record for the "Application Insights" service.

Also, we noticed that the Product Profile and Mapping information between DEV, PPE and PROD are inconsistent.
For the same service, "Application Insights", in DEV there are no products associated with it, in PPE there are 3 products (with the correct names), and in PROD there is 1 product with an blank name.

What could be causing this discrepancies in our data? Could there be a problem with the cloud flow that syncs the Product Profiles and updates the mapping table?

For context, there are 8 rows in PROD with missing Names.

**Comment by JonathanCrd** [comment]
@live1206 could you help us with this issue?

**Comment by live1206** [comment]
For service `Application Insights`, there does exist 2 products mapped to it in [service tree](https://microsoftservicetree.com/services/eb486ec5-6fc7-4507-a12c-cb7fb5a2c461/products)
![image](https://user-images.githubusercontent.com/5196139/215694452-b3add041-2a4d-44b6-b2a0-70701bc0f5fe.png)
But if we take a look at them in CLC:
https://vnext.s360.msftcloudes.com/cloudLifecycle/products?peopleBasedNodes=&global=8:ee5716b5-e6fd-480a-9396-0343b023dfa5&blade=stage:3~kpiowner:All~Domains:All~_loc:cloudLifecycle&actionItemId=
https://vnext.s360.msftcloudes.com/cloudLifecycle/products?peopleBasedNodes=&global=9:0dadfb6f-548a-4c66-9820-72bd707b3cc4&blade=stage:3~kpiowner:All~Domains:All~_loc:cloudLifecycle&actionItemId=
There are no corresponding action items, while we sync products from CLC, if action items are missing, some fields will be empty, so we escape these products.
That's why they do not exist in Dev and Prod, which is correct.

Not sure why they exist in PPE though, we do not remove the existing ones while syncing to add new ones.

Regarding products with empty names in Prod, they were caused with migrating with existing ADO work items. The products did not exist in Prod, and it created a new product during the migration. I will add a check to skip the ones without existing products in [flow](https://make.powerautomate.com/environments/ca95f761-477a-4e98-b34e-dfd5dd03a770/solutions/b964bd16-e780-ed11-81ad-000d3a3419dc/flows/18feb178-09ca-4db9-b1d9-3b039df307d5/details?utm_source=solution_explorer&fromflowportal=true). After that, I will remove the products without empty names in Prod.

**Comment by JonathanCrd** [comment]
@live1206 thank you for the response and thanks for fixing the data in prod as well.

**Comment by JonathanCrd** [comment]
Let me know if there is something we can help you with.
