### ISSUE TITLE
Typo when there is failure to load product list

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-sdk-tools#5233]
Product: PPE-1.0.0-beta.3
Continue is spelt wrong.

![image](https://user-images.githubusercontent.com/5912228/214910752-358cc344-ba38-468c-8714-7138567b12a0.png)

**Comment by mayurid** [comment]
Additive nit: Overall, this UI needs some attention and UX love. I would update the message with "Failed to load...." or "Failure to load....."
Also I am unclear on what are the next steps that i can do if i press continue?

**Comment by JonathanCrd** [comment]
@mayurid thanks for the comments.
I'm gonna fix this as part of https://github.com/Azure/azure-sdk-tools/issues/5699

I'm thinking of replacing 'Failed to load product list' for something else, like 'Could not find any products associated with <your service>'. There are scenarios in which the service does not have any product at all (yet), so it's not like something is 'failing'.

**Comment by JonathanCrd** [comment]
Fixed the typo and improved the message. Also, based on the comments to improve the UX, and discussions regarding https://github.com/Azure/azure-sdk-tools/issues/5699 to make this action more explicit, I got rid of the warning window at all and instead replaced it with an in-line warning message. The submit button will be disabled until the user checks that checkbox.

![image](https://user-images.githubusercontent.com/17486462/230181956-c20159cb-40fb-4662-81e9-c1f1a9f56410.png)

Since we will be working on a UI redesign soon, I tried to follow @ccbarragan design design, so it's easier for us to migrate this alerts in the future. To be clear, I'm not working on the redesign yet.
