### ISSUE TITLE
Beta.3 is calling beta.2

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5256]
In this view when I click either `Data-plane API Readiness` or `Data-plane SDK Release` it opens the apps in version `beta.2` which means that we are mixing environments. I went from `beta.3` which is `PPE` to `beta.2` which is `Prod`

<img width="339" alt="image" src="https://user-images.githubusercontent.com/9868623/215207743-2f9bdd5e-c022-493e-bd0d-10af0caa9130.png">

**Comment by live1206** [comment]
@maririos 
The version does not tie to a specific environment.
![image](https://user-images.githubusercontent.com/5196139/215312381-856816b3-7f16-4721-bfdb-bed80cb0929b.png)
Because we do not want to release beta 3 for user to use in Prod, and also we might want to do a bug fix for beta 3, which is in Prod. We created a new version of the Release Planner App, so, all versions of Release Planner App exist in PPE, beta 1 is deprecated.

The reason why `Data-plane API Readiness` and `Data-plane SDK Release` are beta 2 is because we did not touch them when we were implementing Management-plane Apps. Thye just remained beta 2 as in Prod.

Please let us know if you think we should approach this in another way. Thanks!
