### ISSUE TITLE
Service Level Overview pages should not have parens in the filenames

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#5433]
It looks like the docs site doesn't support including those pages -- https://learn.microsoft.com/en-us/dotnet/api/overview/azure/data-lake-storage-(gen-1)?view=azure-dotnet

**Comment by nickwalkmsft** [comment]
@danieljurek Yes, in !INCLUDE links you need to backslash-escape the close paren character, like `\)`.

**Comment by nickwalkmsft** [comment]
The content for service-level readmes appears to be generated here:

https://github.com/Azure/azure-sdk-tools/blob/7c98f1b4554f73a9e6b53dca7816fc76c80e17cc/eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1#L14-L15

If $indexTableLink has a `)` character in it, it breaks parsing of the !INCLUDE statement on the Docs platform side, and the statement itself ends up in the rendered content instead of the contents of the included file.

The fix is to replace `)` with `\)`.
