### ISSUE TITLE
Improve warning message in Data Plane SDK Release app

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5514]
Improve warning message by including more specific information about who the PM is and how to contact the PM.

![image](https://user-images.githubusercontent.com/9868623/219807552-5d764ee8-5a54-4010-8f3d-f1b06e010b38.png)

@ladonnaq Is this a PM from our team? or any PM? :)

**Comment by JonathanCrd** [comment]
Since our apps have multiple pop-ups, I created a new component to have consistency across them.

I did the required changes for this pop-up.
Clicking on `Email us` will pre-fill the email with the Work Item URL. There's no deep link to do that in a Teams channel.



![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/2c26e083-fff5-4247-8d0f-fe82d1447dd8)
