### ISSUE TITLE
Reword how we create dev branches in OpenAPIHub 

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5657]
![image](https://user-images.githubusercontent.com/9868623/223824847-34ce5686-0631-4267-a957-bdeebe73bc3d.png)

The second option could be interpreted as the branch has all permissions needed to merge into the branch (with no PR to the branch) and no API Spec review, when in reality it does have restricted permissions to merge.

**Comment by maririos** [comment]
Per https://github.com/Azure/azure-sdk-tools/issues/5569#issuecomment-1530277838 also move the current first option to the last option.

**Comment by heaths** [comment]
> Per [#5569 (comment)](https://github.com/Azure/azure-sdk-tools/issues/5569#issuecomment-1530277838) also move the current first option to the last option.

I'd also move the current third option to second. It's generally easier for reviewers to review bite-sized changes to a swagger rather than a huge set of changes all at once. It's easy to miss things in that scenario because everything looks new in a GitHub PR.

**Comment by maririos** [comment]
Order and content:
```
- Create branch without API Spec reviews from archictecs. This branch is protected and will need pull request to make updates to the branch (recommended option)
- Create branch with API Spec reviews from respective architects on all PRs to this branch
- Create unprotected branch without reviews to any PRs to this branch
```

How does that sound @heaths ?

**Comment by heaths** [comment]
Both the first and second option create protected branches. I'd just mention that PRs are reviewed in both cases, but only one by architects:

- Create protected branch that requires API reviews from architects and other reviewers. Pull requests are required to update this branch (recommended).
- Create protected branch that does not require API reviews from architects, but from other reviewers. Pull requests are required to update this branch.
- Create unprotected branch that does not require reviews to any pull requests.

Is that accurate? I'm still confused on when reviews are required vs. not. Ideally, we want them for all PRs, but architects don't necessarily need to review.

It might be appropriate to not mention architects, either. There are a large, diverse group of people on the API Stewardship board that review. Maybe we should just mention the API Stewardship Board instead of "architects".

**Comment by maririos** [comment]
> Is that accurate? I'm still confused on when reviews are required vs. not. Ideally, we want them for all PRs, but architects don't necessarily need to review.

Based on my understanding, yes. 

> Maybe we should just mention the API Stewardship Board instead of "architects".

Good point. we will need to include either `API Stewardship Board` or the `ARM Review board` according to what the user specifies on `Service type`:

<img width="134" alt="image" src="https://user-images.githubusercontent.com/9868623/235540757-d286ced8-5054-4769-b2e0-ac50f8884788.png">

**Comment by heaths** [comment]
Or maybe generalize it to just "review board"? Or maybe that just makes it confusing for our partner.

**Comment by maririos** [comment]
The CI process has changed thanks to all the contributions made by @konrad-jamrozik 
As part of the work @JonathanCrd is doing in https://github.com/Azure/azure-sdk-tools/issues/7829 , the "create branch" from OpenAPI Hub feature will go away and standard documentation will be in our Engineering Hub documentation site.
This issue is no longer applicable
