### ISSUE TITLE
Information discrepancy between ADO and Service Tree

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5796]
Every day, the Release Planner syncs the information from Service Tree to Dataverse.
The Release Planner uses the information from Service Tree and displays it to the user.

When the PMs meet with the Service Partners, some of that information can be updated and get's out of sync with Service Tree and the Release Planner.

@ladonnaq what do you think should happen in this case?

**Comment by ladonnaq** [comment]
@maririos Once the existing work items are imported to dataverse, we can stop manually updating the fields that are updated from service tree.  Today this is manual because we have to often tell service teams to go update their lifecycle metadata in service tree so that the Cloud Lifecycle data is correct, then we have to manually update the work item.  
As far as the data that is in the ADO work item and in the release planner, we should identify any fields that should be bidirectionally synchronized.  As the release planner functionality improves, we should push most data to the ADO work item but in the interim we will have some fields that require manual update and sync to release planner. For example, after onboarding is complete, the following fields are updated manually.  This is because right now we want to confirm scope as TypeSpec + DPG and if the SDK is a new initial or new version.  I believe that this information is used by the release planner to check to see if a service team is "approved" to create a data plane release plan (because right now we only support TypeSpec + DPG).  
![image](https://user-images.githubusercontent.com/67656762/227998275-dd70fe87-e4ba-41d6-a63d-896b74f9d1e5.png).

**Comment by maririos** [comment]
Sounds good. so for now I won't update the ADO items with the information in the Release Planner. And as we start using the RElease Planner, like you said, we can identified which fields need to be synced and in which way

**Comment by ladonnaq** [comment]
> Sounds good. so for now I won't update the ADO items with the information in the Release Planner. And as we start using the RElease Planner, like you said, we can identified which fields need to be synced and in which way

Can you identify what data is currently pushed to the ADO work item from the release planner? This way I can figure out what needs to done moving forward and create a GitHub issue to track.  For example, I know how that the "Onboard Azure SDK launch criteria" is marked "complete" when a service team onboards via the release planner and the ADO work item is created.
