### ISSUE TITLE
CLC link is not created correctly when a service submits Onboarding questinnary

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5920]
Right now, the `CLC Link` value is always hardcoding the value `"https://vnext.s360.msftcloudes.com/cloudLifecycle?blade=&peopleBasedNodes=lorifraleigh_team;scotk_team&global=8:" .
We need to see how to fix this to the CLC link of the service

**Comment by maririos** [comment]
@ladonnaq could you provide an example of what the link is so we can look at it from Eng?

**Comment by JonathanCrd** [comment]
A couple of things:

1. The value is not being hardcoded completely, just the first part of the link is and then we append the CLC ID at the end. This part is not up to date, and that is why the link does not take you to the product page. I fixed it already. 
However, there's a thing to keep an eye on. I found that the query param `global` is usually `global=8:{CLC_ID}` but sometimes is `global=10:{CLC_ID}`. I wonder what that number before `:` means. It seems that changing it does not affect the link, but we should definitely keep this is mind in case it is actually relevant.

2. What would be the desired value to show on the ADO Work Item field? Since the field is an HTML box, I can show a hyperlink, for example: `<a href="{CLC_Link}"> {Product_Name} </a>`. Or would it be better to show the plain URL?

3. And the last thing, what should I write in that field if the product does not have a CLC ID? I understand this should not be possible, but in case it happens, what would be the best way to show this?

**Comment by ladonnaq** [comment]
> A couple of things:
> 
> 1. The value is not being hardcoded completely, just the first part of the link is and then we append the CLC ID at the end. This part is not up to date, and that is why the link does not take you to the product page. I fixed it already.
>    However, there's a thing to keep an eye on. I found that the query param `global` is usually `global=8:{CLC_ID}` but sometimes is `global=10:{CLC_ID}`. I wonder what that number before `:` means. It seems that changing it does not affect the link, but we should definitely keep this is mind in case it is actually relevant.
> 2. What would be the desired value to show on the ADO Work Item field? Since the field is an HTML box, I can show a hyperlink, for example: `<a href="{CLC_Link}"> {Product_Name} </a>`, like [this ADO Work Item](https://dev.azure.com/azure-sdk/Release/_workitems/edit/15866). Or would it be better to show the plain URL?
> 3. And the last thing, what should I write in that field if the product does not have a CLC ID? I understand this should not be possible, but in case it happens, what would be the best way to show this?

1.  I am not sure what difference between global param. Let me know if you want me to ask someone from S360/CLC team. 
2. The ADO work item field for the Cloud Lifecycle link is a single text field.  I think it would be best to put the link in that field as text and someone can copy/paste the link to get to it. 
3. If there is no CLC ID and no CLC link, then leave the field blank for now.  The edge case is when a service is onboarding and there is no products that relate to the work they are doing.  In this case, they would onboard as a service and there would be no CLC record b/c CLC is only products not services.

**Comment by JonathanCrd** [comment]
> I am not sure what difference between global param. Let me know if you want me to ask someone from S360/CLC team.

We can ignore it for now, and if we see issues related to this link in the future, we can contact them.

**Comment by JonathanCrd** [comment]
Finished with the changes requested based on the last comments. 
The CLC link is now fixed and will only be added when a CLC product is onboarded.
