### ISSUE TITLE
Implement new CODEOWNERS syntax for labelling workflow

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#5945]
As in the email thread with subject `RE: (merged threads) Re: Question about the ServiceLabel tags in CODEOWNERS files + Re: Inquiry:  SDK team owners data source`

Relevant snippets:

```
# ServiceLabel: %Event Hubs 
#/<NotInRepo>/            @jsquire, @someother
 
# ServiceLabel: %Event Hubs %Service Attention
#/<NotInRepo>/            @serkant, @james
 
# ServiceLabel: %Event Hubs
/sdk/eventhub/             @jsquire, @somearchitect, @serkant, @otherservice
 
NEW SYNTAX:
# ServiceLabel: Event Hubs
# Service owners:   @serkant @james
# Azure SDK owners: @jsqure @someother
# PR reviewers:
/sdk/eventhubs/     @jsquire @somearchitect @serkant @otherservice
``` 
 
```
# ServiceLabel: %Event Hubs %Service Attention
#/<NotInRepo>/            @serkant, @james
 
# ServiceLabel: %Event Hubs
/sdk/eventhub/             @jsquire, @someperson
 
NEW SYNTAX:
# ServiceLabel: Event Hubs
# Service owners:   @serkant @james
# Azure SDK owners & PR reviewers:
/sdk/eventhubs/     @jsquire @someperson
```

```  
# ServiceLabel: %Event Hubs %Service Attention
#/<NotInRepo>/            @Azure/eh-engineers
 
# ServiceLabel: %Event Hubs %Service Attention
/sdk/eventhub/             @serkant, @james
 
NEW SYNTAX:
# ServiceLabel: Event Hubs
# Service owners:   @Azure/eh-engineers
# PR reviewers:
/sdk/eventhubs/     @serkant @james
```
  
```  
# ServiceLabel: %Event Hubs %Service Attention
/sdk/eventhub/           @serkant, @james
 
NEW SYNTAX:
# ServiceLabel: Event Hubs
# Service owners & PR reviewers:
/sdk/eventhubs/     @serkant @james
```

**Comment by JimSuplizio** [comment]
I'm recommending a few changes to this.

1. There's a missing, existing, moniker in the suggested changes and that's **PRLabel**. We need to keep that. The **PRLabel** and the **ServiceLabel** don't have to be the same and they serve different purposes.
2. **PR Reviewers** - This moniker is completely unnecessary and not entirely accurate. It's tied to the next source/owner line in the CODEOWNERS. These are the owners of that source for that path, and they're automatically added to a PR if files in that path have been changed provided that the repository is setup that way. This is something GitHub does, not us. It's literally something that would be completely ignored in parsing as we're already parsing the owners without this moniker.
3. Removal of spaces in any new monikers. The old monikers, **PRLabel** and **ServiceLabel**, don't have spaces and the new monikers, **AzureSdkOwners** and **ServiceOwners** will not either.
4. No compound moniker lines. I will not be implementing "Moniker1 & Moniker2" syntax. This just makes processing that much more of a pain as now each moniker needs to know how to deal with other monikers. Every moniker needs to be on its own line.
5. Fall through vs duplicate data. An example of fall would be if the moniker # ServiceOwners: with no entries appears just above a source/owner line, the service owners would be pulled from the owners in the source/owner line instead of the moniker always having their owners declared on the same line. I'm a bit torn here; on the one hand duplicate data is explicit, on the other hand fall through has more potential for people to foul things up. For example, [Java's CODEOWNERS](https://github.com/Azure/azure-sdk-for-java/blob/main/.github/CODEOWNERS#L45) file has one PRLabel over a group of source/owner lines and I'm reasonably certain they're expecting that label to apply to all of those lines but that's not the case. Only the first source/owner line after the **PRLabel** gets the label, the rest do not. **ServiceLabel** is the same in this case. If we're going to do fall through, then it needs to be abundantly clear that _every source/owner entry needs its own set of metadata_ with the following rules:
  a. Label monikers always need to have their labels defined.
  b. Owner monikers need their owners defined on the same line unless they're immediately above a source/owner line at which point it'll use those owners.
  For example:
  \# AzureSdkOwners:
  \# ServiceOwners:
  /sdk/SomeServiceDirectory @user1 @user2
 If we did this then AzureSdkOwners, ServiceOwners and the source owners would all be user1 and user2.
6. The ServiceLabel and ServiceOwners combination will be replacing the ServiceLabel/NotInRepo combinations that exist today. 

These new monikers, specifically the owner monikers, will fundamentally change the CodeownersParser. Right now, a CodeownersEntry consists of a path expression, ServiceLabels, PRLabels and a ubiquitous list of owners. This will have to change as there can now be 3 distinct lists of owners. It'll be interesting doing these updates as the github-event-processor changes will have to be in lock step with these updates.

**Comment by weshaggard** [comment]
>For example:
# AzureSdkOwners:
# ServiceOwners:
/sdk/SomeServiceDirectory @user1 @user2

In your example do we need to explicilty list AzureSdkOwners and ServiceOwners? Should we instead just make them implied based on the path line and have people only provide them if they need to contain a different set of users.

**Comment by weshaggard** [comment]
I don't have a strong opinion but if we have something like:
```
# ServiceLabel: %Foo
/sdk/SomeServiceDirectory @user1 @user2
```

In this case I would have set the ServiceOwners to the 2 users but if there is no service label then no ServiceOwners.

**Comment by konrad-jamrozik** [comment]
> I don't have a strong opinion but if we have something like:
> 
> ```
> # ServiceLabel: %Foo
> /sdk/SomeServiceDirectory @user1 @user2
> ```
> 
> In this case I would have set the ServiceOwners to the 2 users but if there is no service label then no ServiceOwners.

I would interpret it the same way.

**Comment by JimSuplizio** [comment]
> the existing parsing does that inference if the source/path entry has a ServiceLabel.

@weshaggard, you are 100% correct, this is exactly what the Codeowners Utils does now and will be documented accordingly.

**Comment by JimSuplizio** [comment]
A [parser/linter](https://github.com/Azure/azure-sdk-tools/tree/main/tools/codeowners-utils) was built to deal with the new syntax. Linter pipeline have been created and enabled for all of the repositories, including baseline error files. The updated InitialIssueTriage rule was written and subsequently disabled lacking the metadata to be used effectively.
