### ISSUE TITLE
Can no longer submit onboarding for a service with no product 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6020]
I met with the Azure Migrate team today.  They have new ARM namespace and new management plane REST API Spec but the work is not associated with a new product.  I tried to onboard Azure Migrate service but the submit button is greyed out.  This was working previously as we have onboarded new services that do not have products yet and also onboarded teams that are working on non-APEX related work.  

![image](https://user-images.githubusercontent.com/67656762/233473655-af265f46-0126-4710-b6f2-bcb6c8f46971.png)

**Comment by ladonnaq** [comment]
@JonathanCrd @maririos - It seems I can no longer onboard a service without a product.  This was working previously.

**Comment by JonathanCrd** [comment]
Actually, as we discussed, this use case is not covered by the onboarding questionnaire. Since the team does have at least one product, it won't allow the user to continue until selecting one.

Before making changes, I need to understand all the different possible scenarios in order to have a better design. I am keeping track of this discussion here: 

- https://github.com/Azure/azure-sdk-tools/issues/6059

**Comment by JonathanCrd** [comment]
As we discussed offline, this is part of uncovered scenarios for certain teams. I'm closing this issue in favor for #6059.
