### ISSUE TITLE
Linting PR descriptions/titles for quality

### ISSUE THREAD

**Issue by xirzec** [Azure/azure-sdk-tools#6087]
Something I've been struggling with as a reviewer is when PRs don't provide enough context about the change being proposed, both the motivation behind the change and why the specific design was chosen. Also I've noticed when debugging problems, it's frustrating to look at the git history and find a lack of details about why a specific section of code was added.

In JS we tried to address this with a PR template, but folks sometimes blank out the template rather than fill it out or (even worse) leave the template totally empty when they submit it.

To address this without becoming a mean and spiteful reviewer, I have been working on the idea of having an automated lint check for PRs that could help raise the minimum bar.

I wrote up a rough gist for what checks might be useful here: https://gist.github.com/xirzec/552a1d94ae0220575635608232ea7655

I didn't get a ton of feedback on it, but I wanted to start gathering evidence of if such automation was useful, so I wrote a GitHub action that implements the checks I felt were important: https://github.com/xirzec/pr-lint

Some of them are pretty simple, like the PR body not being empty: https://github.com/xirzec/pr-lint/blob/main/src/rules/noEmptyBody.ts

Others are more complex like the PR title containing an area in square brackets that may be a service name (from the folder path) or the package name (also from the folder path): https://github.com/xirzec/pr-lint/blob/main/src/rules/titleContainsArea.ts

GitHub Actions don't seem to have a test framework yet, but I wrote some tests against the validation rules directly: https://github.com/xirzec/pr-lint/blob/main/test/validation.spec.ts

While I'm sure all languages have similar needs when it comes to improving PR quality, my approach was to attempt this as an MVP in the JS repo before modifying the common automation for all repos or making it a "required" step: https://github.com/Azure/azure-sdk-for-js/pull/25731

@jsquire pointed out that there are some GitHub API limits, so I want to make sure our experiments don't burn unnecessary resources. 

I also acknowledge that the EngSys team is a bit busy right now, so ideally I'd like to proceed in a way that allows the JS team to make progress on this feature without placing any kind of undue burden on EngSys folks during Gallium. 😄

**Comment by kdestin** [comment]
To lend some more evidence to potential impact, the ML team in the Python repo also experiences many of the same pain points w.r.t PRs lacking documentation and would welcome some form of linting that encourages developers to fill in PR templates.

**Comment by kdestin** [comment]
To chime in in support of this, the ML team in the Python repo has many of the same issues w.r.t documentation in PR descriptions and a linter would be welcome.

**Comment by JimSuplizio** [comment]
@xirzec, as per our chat and the email I'm going to close this out. For everyone else;
Actions are not the correct place to verify PR/Issue descriptions and content. The reason being is that by the time an Action processes, whatever is not correct in the title or description has already been submitted and there's really not much we can do about it at that time. This is something that needs to be enforced prior to the user hitting submit.

GitHub is implementing [Issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) which is still in beta and it’s unclear if this will also be implemented for PRs. The interesting thing here is that instead of the template being in a markdown file, it’s all defined in yml (which isn’t in the workflows directory but the .github/ISSUE_TEMPLATE directory) but does offer some good options. The downside is that it’s beta and unclear if/when Pinocchio will become a real boy or PRs will have something similar.
o	You can declare different types of fields (textarea, dropdown, checkboxes etc.)
o	Fields have a required attribute (true/false)
o	You can turn off the ability to use a blank template
