### ISSUE TITLE
[APIView] TypeSpec APIView incorrectly skips PRs with changes to Shared/*.tsp

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#6108]
I recently created a PR which only made changes to a `*.tsp` file under the `Shared` folder:

https://github.com/Azure/azure-rest-api-specs/pull/23836

It appears that TypeSpec APIView skipped this PR, because it didn't think the `Shared` folder is part of a "project":

```
Find the root directory for specification/contosowidgetmanager/Contoso.WidgetManager.Shared/main.tsp.
Modified file path specification/contosowidgetmanager/Contoso.WidgetManager.Shared/main.tsp is not part of any project.
Modified files are not part of any TypeSpec project. Skipping the step to generate API review.
```

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2754895&view=logs&j=e37a1bb9-a190-5269-3a0e-37469dfbe682&t=09cb0672-20c5-5dce-4552-dad3f3e96fd3&l=16

**Comment by chidozieononiwu** [comment]
The problem here is that there is no `tspconfig.yaml` file in that directory. the logic uses the presence of that file to determine if its a TypeSpec project directory. See [here](https://dev.azure.com/devdiv/DevDiv/_git/openapi-alps?path=/public/rest-api-specs-scripts/src/utils.ts&version=GBopenapipipeline/UpdateLinkText&line=1135&lineEnd=1136&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) and [here](https://dev.azure.com/devdiv/DevDiv/_git/openapi-alps?path=/public/rest-api-specs-scripts/src/utils.ts&version=GBopenapipipeline/UpdateLinkText&line=1164&lineEnd=1165&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)

**Comment by chidozieononiwu** [comment]
A fix has been made for this. We will monitor APIView failures to ensure it was resolved.

**Comment by konrad-jamrozik** [comment]
Related PR with a fix:
https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/487625
