### ISSUE TITLE
[docs] preview supersedence should remove metadata JSON files

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#6204]
`Update-DocsMsMetadata.ps1` should delete those files when a superseding GA version releases.

Also we need to clean up metadata JSON files that have a superseding GA version in the repos and ensure that onboarding is correct.

**Comment by JimSuplizio** [comment]
CC: @weshaggard @kurtzeborn 
@danieljurek I don't think this is necessary. The docs have the latest released GA (if there is one) and the latest released beta. If LibraryA, which was in beta, releases GA there's no harm in leaving both there. Just because something releases a GA doesn't mean everyone using the beta is going to jump to the GA version. For this reason alone, we should be keeping both sets of docs around. Also, the docs are divided into Latest, Preview and Legacy and it's easy to see which one you're looking at. 
![image](https://github.com/user-attachments/assets/6469d302-0af5-4b2b-b14d-57eeb2368e90)

The other thing that this would end up doing, if we removed the preview when the GA released, is that it would cause the daily docs to have to onboard the preview package all over again for scheduled builds, which are most certainly building betas. This only affects the daily docs builds. For deprecated libraries we already move things into legacy from latest or preview, so this isn't problem for that.

**Comment by JimSuplizio** [comment]
@danieljurek and I chatted about this and this isn't going to change. The docs for GA and beta are separate and there's no harm in leaving the last beta docs, prior to the GA, around. Ultimately, a new beta will release that has a higher version than the GA version, prior to the next version release.
