### ISSUE TITLE
TypeSpec APIView is missing content

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#6223]
The [TypeSpec APIView for PR 23627](https://apiview.dev/Assemblies/Review/e76ea2b2ab1543edb7edbd2e31cd8ddd) only shows the very top level of the TypeSpec but none of the operations or models.

<img width="862" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/85643503/6a986b84-faa6-42a1-95bb-173c9571262a">

**Comment by markweitzel** [comment]
From an API Stewardship Board Review: https://github.com/Azure/azure-rest-api-specs/issues/23157

**Comment by tjprescott** [comment]
This behavior is by-design. The namespace `Proposals` (for example) needs to be a subnamespace of `Microsoft.ManagedCcf`.

The reason this is the standard behavior is because otherwise everything in Azure.Core would be rendered in APIView, so it only displays things that are within the service namespace.

**Comment by tjprescott** [comment]
I left comments on the underlying PR to move the offending namespaces and models into the `Microsoft.ManagedCcf` namespace.
