### ISSUE TITLE
TypeSpec validation fails and what to expect if user selects request suppression

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6225]
TypeSpec validation failed, no errors but warnings found in the PR details.  Since this is in production with real service team's PR, I did not want to choose request suppression without understanding what that would do.  What does this do?  Is it okay for me to select this option and see if the API readiness is still blocked?  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/0faf624a-1d71-49b6-8461-9c976fc775f2)

**Comment by maririos** [comment]
In this specific case, we can't request supression because the warnings are telling us that their TypeSpec files need to be updated to be compliant with tooling in `main` branch. 
I created issue for Eng Sys to follow up on the warnings vs error reporting => https://github.com/Azure/azure-sdk-tools/issues/6231

@praveenkuttappan coudl you answer the `Reuest supression` questions here? Also adding, do we show `Request supression` for any failed pipeline? I don't see how we can request exception for a `TypeSpec Validation` job

**Comment by praveenkuttappan** [comment]
We have removed the option to request suppression.
