### ISSUE TITLE
[OpenAPI Hub] Can we remove OpenAPI Validation tools section in main page?

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6236]
In the main page, there is a `Tools` section which contains `OpenAPI Validation Tools` => https://portal.azure-devex-tools.com/tools/validation/menu
- The first 2 static tools (View linter validation results, View semantic and examples correctes of your specs) are not bringing any information, which makes me think it is safe to hide. If someone complains, we can evaluate why they need it and re-evaluate the purpose of it
- Publish PR is already present in the main `Tools` page so no need to have it here
- `Live Validation Tools` Is already in the main page, so no need to repeat

**Comment by praveenkuttappan** [comment]
@JonathanCrd It's already done. right?

**Comment by maririos** [comment]
Not yet

**Comment by JonathanCrd** [comment]
> The first 2 static tools (View linter validation results, View semantic and examples correctes of your specs) are not bringing any information, which makes me think it is safe to hide. If someone complains, we can evaluate why they need it and re-evaluate the purpose of it

I tested them out and it seems they are working fine. However, it takes a long time to load, which made me wonder if it was working at all. I am not aware of the usage and popularity of these two tools, but I would suggest to keep them unless they start failing, or if you think they're not being used at all.  We could improve the loading screen to avoid confusions (put a loading bar or something), but I think it is not worth it.

> Publish PR is already present in the main Tools page so no need to have it here
True, and I don't think it has something to do with the validation right?

> Live Validation Tools Is already in the main page, so no need to repeat
Not the case anymore, however, as part of https://github.com/Azure/azure-sdk-tools/issues/6880 I'm deleting this whole section since this service has been discontinued.

So, what do you think @praveenkuttappan  @maririos ? Should we keep the static tools? or delete this whole section from the portal?

**Comment by maririos** [comment]
> True, and I don't think it has something to do with the validation right?

Correct. At minimum we can remove it from here so there is only one entry and that is the main page.

Are the `View linter validation results, View semantic and examples correctes of your specs` available in the main page? or they exist only in this subpage?
What type of information do you get from each tool? it might be good to check with Konrad and or ScottB and see if they are aware of these static tools and their usage.

**Comment by JonathanCrd** [comment]
I have talked with @scbedd and @konrad-jamrozik and checked the metrics we have available. Both of them mentioned that these results can be obtained by submitting a PR against the Repo, or running OAV locally. If we plan to remove them, we should tell the users how they can obtain these results by themselves.

Also, I checked the telemetry data and it seems that 2 users used the Semantic Validation tool in the past 30 days, while 80 others used the Lint Diff tool. However, it’s important to note that the data might not be accurate due to the possible misconfiguration of the telemetry service.

My suggestion is:

1.  Open a first PR to:
    1. Remove the Live Validation tool since that's already deprecated.
2. Then, open a second PR to:
    1. Add a warning in the sub-menu to let the users know that the static tools will be deprecated, and point them to some docs on how they can run them by themselves.
    2. If there are no docs for this, create them (maybe in Eng Hub?)
3. Later we can remove the whole sub-menu and just leave a link to the docs for the static validation tools.

@maririos @praveenkuttappan  what do you think?

**Comment by maririos** [comment]
PR: https://devdiv.visualstudio.com/DevDiv/_git/openapi-portal/pullrequest/529404

**Comment by JonathanCrd** [comment]
Also, removing the OpenAPI Hub links from the CI docs:

- https://github.com/Azure/azure-rest-api-specs/pull/27845

**Comment by JonathanCrd** [comment]
> Later we can remove the whole sub-menu and just leave a link to the docs for the static validation tools.

Now are in the last step of this task. we can remove the tools completely.
PR: https://devdiv.visualstudio.com/DevDiv/_git/openapi-portal/pullrequest/530311

**Comment by JonathanCrd** [comment]
Released to PROD
