### ISSUE TITLE
Add default users to prod release plans

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6237]
Share Release Plans created in PROD with the v-team so we can help diagnose problems and look at behaviors, specially while we do our initial rollout.
Ideally, Release Plans shouldn't have any permissions and anyone can access them

**Comment by JonathanCrd** [comment]
Both options to add default users to all release plans or removing the permissions would take the same amount of work. Since the future goal is to remove those permissions, I would suggest start removing them.

I have a question, in the Release Plans list view, what should be the filter? Only show the release plans for products from the selected service? Or show all of them? How could we avoid having too many records that are not relevant for the user?

**Comment by maririos** [comment]
> I have a question, in the Release Plans list view, what should be the filter? Only show the release plans for products from the selected service? Or show all of them? How could we avoid having too many records that are not relevant for the user?

Great question. Having all will be too much noise. Filter by the service selected will work for our users (and not for the admins).
@ccbarragan how is this handled in the new UI?

**Comment by JonathanCrd** [comment]
As a first step, I modified the list of the Release Plans and now it shows all the release plans for the selected Service.

Also, I removed all permissions restrictions in the Release Planner APP, however, we must do the same for all other apps, since there is logic in them relying on users' permissions. To avoid this, the current users get added as an owner of the release plan whenever they click the link to open any Readiness App.

Opening this GitHub issue to keep track of those changes:
https://github.com/Azure/azure-sdk-tools/issues/6369

**Comment by JonathanCrd** [comment]
I forgot to summarize the changes that were made here. This is what changed:

**In the Release Planner App**

- Brand new List of the release plans
   - Shows all the release plans for the selected service, not only the ones that are owned by the user
   - Searchable by: Name, Lifecycle stage, Product name, API type, Created by and Status.
   - UI enhancements: Responsive, cleaner, and leans toward the new proposed UI for the App.
- Added Deeplink support for release plans
   - Release plans can be directly opened from a URL.
   - In the new "Summary" screen, added an option to copy a URL to easily share the current release plan
- Added a warning in the Permissions section for a Release Planner, saying that permissions are getting deprecated in future versions, and there's no need to manually add users there anymore.
