### ISSUE TITLE
Live test resources should be deployed and removed independent of agent time

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#638]
It may be possible to use "server tasks" to deploy and remove resources: https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/servertaskauthoring.md

These tasks could run before and after the agent runs to make more efficient use of agent resources.

**Comment by heaths** [comment]
You'd still need a repo to get the files. You could separate `dotnet build` and `dotnet test` (the latter takes a `--no-build` option if you don't want to rebuild again, though it generaly should no-op), then have parallel jobs for `dotnet build` and test resource provisoining, both of which are dependents of `dotnet test`. You'd have to marshal and re-set environment variables in any case if not in the same job (on the same agent), so that's a wash.

For deprovisioning, we could modify the script to start resource group deletion as a job and return control immediately - not wait for it to actually finish. Once the request is sent to the service, there's really no reason to wait for it to complete and we can clean up agents faster.

/cc @weshaggard

**Comment by weshaggard** [comment]
@danieljurek and I chatted a little about this and while we could potentially increase complexity and introduce some sort of "caching" system for provisioning our test resources I don't want us to spend anytime on that until we have evidence that the provisioning is the largest bottle neck or lowest hanging fruit to increase performance of our live test runs. 

I agree with your points as well @heaths in order to provision we will need the repo to get the templates and call the scripts and I don't know that we can do that in a server job and even if we did we would need to have a way get the secrets onto the other agents. So we would have to have some secure way to pass that information between agents.

For deprovisioning if we do start to notice it taking too long then switching to an async model would be an easy thing to try there.
