### ISSUE TITLE
Documentation to clarify prerequisites for first GA of Management Plane SDK

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#6451]
Hi LaDonna, I am looking for the timing to make it clarified to service partner who is targeting to release first GA of Management Plane SDKs.  

The prerequisites of first GA releases are

•	Per [Policies: Releases | Azure SDKs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.github.io%2Fazure-sdk%2Fpolicies_releases.html%23beta-releases-and-stable-graduation&data=05%7C01%7Cyiqiu%40microsoft.com%7Ce7fe5a87d08d4ea749f908db7c370489%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638240348006160800%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hbmDRpKZIikiScUvyuxGbNLOTKorzE4tMiio%2B4rWfBA%3D&reserved=0), the service/feature must have a beta release available for at least one month to allow for community feedback. Other details, may refer to the SDK release policies further.
•	The service/feature team must explicitly agree no breaking change to GAed libraries.  “Explicitly” means if we can keep a recording of their commitment when they approaching first GA? And we shall let the team know the consequence – If you introduce any breaking change to GAed libraries, you may have to work on the breaking changes in the future SDK releases manually.  We truly hope this can reduce breaking change number and frequency, which bothers us a lot, refer to the breaking change analysis attached below
•	The service/feature team must ensure coverage of 5 supported languages – Python, Java, JS, Go, .NET.  For .NET management plane SDK,  the service/feature team need to work on the SDK code, tests, samples, and create a pull request in [the SDK repo](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net&data=05%7C01%7Cyiqiu%40microsoft.com%7Ce7fe5a87d08d4ea749f908db7c370489%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638240348006160800%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rUeNj9WSGdMut7n1in8ATfubH%2F8jtE0cm7fawXVYvF0%3D&reserved=0) for SDK code review and signoff before release.  Ensure to save at least 4 weeks working on .NET management plane.  

Where do you think best put these clarification?  Looking forward to your guidance here.

===============================
Breaking Change Analysis of Closed Spec PR from [https://aka.ms/azsdk/mgmt-sdk-monthly](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazsdk%2Fmgmt-sdk-monthly&data=05%7C01%7Cyiqiu%40microsoft.com%7Ce7fe5a87d08d4ea749f908db7c370489%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638240348006160800%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4z79AxVFISPHJYYrDk85JOjEZlAJDzrm43e%2FlzF4SRI%3D&reserved=0)

![image](https://github.com/Azure/azure-sdk-tools/assets/18413981/b8cb50df-1b67-41a5-98c3-3149d4040eb4)

**Comment by ladonnaq** [comment]
Hello @josefree - In the SDK release app we a step for sign-off.  That is where we automatically check requirements that we are able to do so right now and then we are collecting the other evidence via form and will still have to manually go validate.  

This is the sign-off for new initial beta for management plane are as follows: 

- API readiness must be completed for the pull request for the API Spec that will be published as first preview API Spec.  (This is done via the Release Planner)
- Link to the GitHub issues tracking the namespace review and approval for the management plane packages.  (Manual right now, I would like to automate by asking Ronnie if he can add labels so that we can confirm that this step is complete.) 
- Link to the .NET pull request that is being used to work on the release work. (Manual right now.  We have to look at the PR to make sure that the test, samples, etc are complete or near completion) 
- Link to the GitHub issue that is created when the team request review of the initial .NET SDK by the arch board.  (Manual right now.  It would be good if APIView was used to approve the .NET APIView so that we can automate). 
- Link to the APIView for .NET SDK that is being reviewed by the arch board. 
- Links that are generated by OpenAPI Hub for the release of Java, JavaScript, Python, and Go.  (Manually check after target SDK release date to make sure SDKs were released. We may be able to automate this by creating a report that identifies the package work item state against the SDK target release date at some point in Ge semester). 

This is the sign-off for new initial stable release is similar with a few changes: 
- There is no namespace check because that should be done in Public Preview.  Should we do a check to confirm that it is was done earlier?   
- All the rest is the same.  As I understand every stable release of .NET requires arch board approval.  Please let me know if this is not correct.

**Comment by maririos** [comment]
@ladonnaq  Is there an action item here for Engineering on the SDK apps?

**Comment by josefree** [comment]
@ladonnaq this request only documentation clarification.  I am looking for a proper location to place this docs clarification on prerequisites for first GA of Management Plane SDK.  It can be a self-check before submitting an SDK release request.  

Besides what I have mentioned in the first comment.  There are some new perquisites related to TypeSpec in place.

The goal for Ge for the Swagger  Typespec conversion is the following:-
•	Any new Data Plane or new Management plane services that are happening in the Ge time frame will be authored using Typespec
•	Any existing new Data Plane or Management Plane service which has not GA’d yet should be authored using Typespec.
•	Any existing Data Plane or Management Plane service which are doing a major upgrade such that Breaking Change Board have approved them for breaking changes are candidates for Typespec. Example: Form Recognizer

**Comment by maririos** [comment]
@josefree 

> @ladonnaq this request only documentation clarification. I am looking for a proper location to place this docs clarification on prerequisites for first GA of Management Plane SDK. It can be a self-check before submitting an SDK release request.

My recommendation is to add this requirement to https://eng.ms/docs/products/azure-developer-experience/develop/sdk-release
As you can see, there is already other information there the user needs to be made aware of. You can create a PR and improve the docs.

In the Release Planner we don't know if the user is doing a first GA. We just know it is a GA. We could consider adding this to the UI too as a way to reinforce the message. Will it be ok if it is for all GAs?

**Comment by maririos** [comment]
updated: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-generate-mgmt-dotnet

**Comment by ladonnaq** [comment]
Since docs are updated I am going to close this issue.  I have opened another issue to track related work on this topic - https://github.com/Azure/azure-sdk-tools/issues/7492.  We do need to look into asking user's to validate in the create release plan flow (new initial SDK or new SDK version) as the requirements are different for new initial SDK releases (beta and stable).
