### ISSUE TITLE
[IssueTriageBot] Service contacts are not tagged when 'service attention' label is added

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#6474]
After the fabric bot is replaced by github action, the service team contacts are not being tagged when both of `area` label and `Service Attention` label are added to the issue across all SDK language repos. This blocks the service team to be notified on the SDK repo issues.

These are two examples: [JS repo#26411](https://github.com/Azure/azure-sdk-for-js/issues/26411), [Go repo#21004](https://github.com/Azure/azure-sdk-for-go/issues/21004).

//CC: @JimSuplizio , @weshaggard

**Comment by raych1** [comment]
This issue doesn't expect the `need-triage` label to be added, instead it expects the pre-configured github contacts or github team would be tagged by comment in the issue.

**Comment by JimSuplizio** [comment]
// CC @weshaggard @kurtzeborn 
@raych1 I've updated the CODEOWNERS in Go to add the entries that were in the FabricBot rule. I'm currently looking entries for Java, JS, Net and Python limited to discrepancies between the FabricBot rule and what's in their CODEOWNERS. The JS example issue that you'd linked wouldn't have added people for the OpenAI label because that label didn't exist in the FabricBot rule and there's no ServiceLabel entry for it. There is a [PRLabel entry for OpenAI in the azure-sdk-for-js CODEOWNERS](https://github.com/Azure/azure-sdk-for-js/blob/main/.github/CODEOWNERS#L171) and if the owners are the same, I'd recommend you add the following line before or after the PRLabel entry.
**# ServiceLabel: %OpenAI**
If there are different owners for the service then you'd add the following entry
**# ServiceLabel: %OpenAI**
**#/<NotInRepo>/          @owner1 @owner2**

**Comment by JimSuplizio** [comment]
Removed the needs-triage as I'm actively working on this.

**Comment by JimSuplizio** [comment]
As for the other repositories, the ones with this same rule in FabricBot, I've created PRs to update the CODEOWNERS files' ServiceLabel entries. I'm reading the FabricBot.json file from the PR in which it was removed and updating the CODEOWNERS files with missing entries. The respective language PRs, for the ones requiring updates, are:

- [Go](https://github.com/Azure/azure-sdk-for-go/pull/21176)
- [JS](https://github.com/Azure/azure-sdk-for-js/pull/26500)
- [NET](https://github.com/Azure/azure-sdk-for-net/pull/37638)
- [Python](https://github.com/Azure/azure-sdk-for-python/pull/31159)

Since I've already given instructions on how to fix the missing OpenAI label, I'm going to close this out.

**Comment by raych1** [comment]
Thanks @JimSuplizio , how about java language repo?

**Comment by JimSuplizio** [comment]
> Thanks @JimSuplizio , how about java language repo?

azure-sdk-for-java repository didn't require changes. The entries in the FabricBot.json had matching ServiceLabel entries in the CODEOWNERS and didn't require the updates that the other languages did.
