### ISSUE TITLE
Release planner - Update ADO work item to mark release plan completion

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#6587]
Update API readiness and SDK release plan as completed in ADO work item. Ideally all work items under the release plan should also be in completed status when a release plan is completed.

**Comment by maririos** [comment]
For now, only Private Preview will be able to be completed as the SDK app is not in use yet

**Comment by maririos** [comment]
@JonathanCrd because you are working on the API Readiness apps, let me know when youa re not using one and I will do the changes in that one

**Comment by maririos** [comment]
After looking more into it, I decided to not do automation and wait for PM team to close/update the work items manually as I think we don't have enough information yet. For example, for private preview, we still need to check that the PR was merged into main in order to be able to close the API Spec work item. This might happen after they used the API Readiness apps, at which point our automation is no longer available.
I am going to move this issue to backlog

**Comment by maririos** [comment]
@praveenkuttappan this is already done, right?
