### ISSUE TITLE
Service Partner cannot find their product in the drop-down box

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6646]
Service partner is trying to onboard - https://microsoftservicetree.com/products/79902ba0-cc00-4a47-b260-077162929448 but it is not showing up in the drop-down box. 

Any ideas?  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/9ffda30e-534a-476e-b2a5-8f73c26244c5)

**Comment by maririos** [comment]
I looked into this and I wonder if the product name changed recently? According to the screenshot you can see how the name was modified today after automation ran. 
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/7b2ccd02-afd2-4cb7-befc-60af4ff3c03f)

As of previous records, the SKU ID is the same as the one for `Voice Intelligence`  .
Also, they have already onboarded and have workitem: https://dev.azure.com/azure-sdk/Release/_workitems/edit/14927

**Comment by maririos** [comment]
@ladonnaq so we could wait until tomorrow and see if the name gets updated in our records too... but also, if they wanted to onboard, they already have

**Comment by msft-andrew** [comment]
[Replying directly, to save the redirection]

Thanks for looking @maririos - the "evolution" of my Service is:
- `Mount Calm`
- `Voice Intelligence`
- `Valmora` (only changed to this, this week)

I should note that even when it was called `Voice Intelligence`, I looked at (last week) "Onboarding" but still couldn't see my Service. Maybe these renames are causing issues?

...but it sounds like even though the name has changed, because the SKU ID is the same, that onboarding task might still be valid. Do you agree? https://dev.azure.com/azure-sdk/Release/_workitems/edit/14927

I don't seem to be able to create a Release Plan either - e.g.
![image](https://github.com/Azure/azure-sdk-tools/assets/137055506/e8dc008b-b0ee-4d26-9436-983d6ec8a02a)

...so I'm a bit worried I'm stuck in a bad state!

**Comment by msft-andrew** [comment]
Huh, I've only just seen that @ladonnaq screenshot looks different to mine - it has a different SKU listed in the dropdown. Is it related to having multiple SKUs in the development phase?

**Comment by maririos** [comment]
Names have correctly updated in our tooling. @msft-andrew onboarding looks good and you should be able to create a Release Plan.
It looks like you are using a different Service Name than the one that is attached to the product you want.
Following the name and ID on service Tree for your product, this is what I see in the screen (which is the same as La Donna and the Onboarding Work Item):

![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/c3dbb02d-67ec-4608-866b-0893b3e7f4c0)

**Comment by msft-andrew** [comment]
Aha - you're right! I was looking at `Azure Communications Gateway`, because my reading of https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/807/Lifecycle-Requirement-API-design-and-API-readiness?anchor=create-a-release-plan made me think that "the top-level service" I should be selecting should be the Offering, rather than my own Service. Perhaps I am being naive.

**Comment by maririos** [comment]
@msft-andrew  To confirm. you are ublocked now, right?

**Comment by msft-andrew** [comment]
Right. No action needed, unless you also think there should be some docs tweaks to save this confusion happening again 😸
