### ISSUE TITLE
[APIView] Error in AppInsights

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#6663]
Some nuget packages may contain 0 DLLs, we need to handle this.

https://github.com/Azure/azure-sdk-tools/blob/19ca6ea1647e7bebfe1a7583ddcd8bc5c3087bb8/src/dotnet/APIView/APIViewWeb/Languages/CSharpLanguageService.cs#L65

**Comment by JoshLove-msft** [comment]
What is the use case for creating an Api View with 0 dlls? I know there are meta packages like this - for instance, https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage, but there would be no API to review if there is no dll. Ideally, we could just not create reviews for these and still ship them, which I suspect is the current process because creating a review for such package results in an error.

**Comment by JoshLove-msft** [comment]
@chidozieononiwu, @maririos are 0 dll Api Views needed to ship metapackages? Or can this be closed if we have an alternate process in place for such packages.

**Comment by maririos** [comment]
Need to confirm with architects. If they are ok with it we will need to stop generating the APIView and not fail the pipeline

**Comment by chidozieononiwu** [comment]
Resolved in https://github.com/Azure/azure-sdk-tools/pull/7519
