### ISSUE TITLE
Docs onboarding v2 cleanup tasks

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#6800]
Cleanup tasks: 

* [x] - Delete onboarding-specific code from Language-Settings.ps1 
* [x] - Move validation code to Docs-Onboarding.ps1 
* [x] - Remove Update-DocsMsPackages.ps1 (the old v1) 
* [ ] - Rename method with trailing 2 in Update-DocsMsPackages.ps1
* [x] - Migrate package names from `.txt` file to metadata JSON file for Java 
* [x] - Investigate deprecated packages whose metadata JSONs don't match the versions

**Comment by danieljurek** [comment]
Still some work to do here but don't want to cause merge conflicts for Python and Java which have PRs in flight.

**Comment by JimSuplizio** [comment]
I checked the checkbox for "Migrate package names from .txt file to metadata JSON file for Java" which was fixed with the following PRs

1. azure-sdk-for-java - [Put the namespaces(packages) into the json files](https://github.com/Azure/azure-sdk-for-java/pull/39593) 
2. azure-docs-sdk-java - [Remove defunct .txt files and template libraries added via testing](https://github.com/Azure/azure-docs-sdk-java/pull/2542)
