### ISSUE TITLE
Should Review meeting have a Release Plan attached to it?

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6819]
In order to populate information correctly, we need to know which Release Plan is associated with a meeting.
How should we get this information?

**Comment by maririos** [comment]
This applies to the SDK review meetings too

**Comment by maririos** [comment]
After talking to @ladonnaq we agreed on:
- Adding a field in both API Review and SDK Review to show the Release Plans that are attached to a product and let the user select one. Only then, we will populate the API Spec information.
- Hint the user to create a Release Plan if there isn't one created or one that works for them.
- Add this functionality only for users that select products

**Comment by JonathanCrd** [comment]
> Hint the user to create a Release Plan if there isn't one created or one that works for them.

With these changes, are we going to prevent the users from scheduling review if they don't have a Release Plan for their product? Or is this more like a suggestion?

**Comment by maririos** [comment]
> Or is this more like a suggestion?

For now, it is going to be a suggestion. Once the Release Plan supports creating release plans for all scenarios we can make it mandatory. Or when we have more confidence this is the route we want to take

**Comment by ladonnaq** [comment]
@maririos Has the prompt to ask user's to provide link to release plan been added to the API Review and SDK review meetings yet?  If not, we should prioritize implementing this and all teams using TypeSpec should have a release plan.  We should wait until this issue is resolved as teams working on non-APEX work for APIs/SDKs that were GA prior to April 2022 are  blocked from creating release plans because their products are not showing up in the drop-down box of the release planner app - https://github.com/Azure/azure-sdk-tools/issues/6638.

**Comment by maririos** [comment]
It has not, and it is one of our priorities :)

**Comment by maririos** [comment]
Ideas to implement this by Crystal are based on: https://fluent2.microsoft.design/components/web/react/dropdown/usage
She suggested to add a dropdown when the team selects a product and list the release plans. Also have an option to go to docs and create one in case there isn't one

**Comment by JonathanCrd** [comment]
> If the dropdown can contain multiple information we chould show the release plan number and other important field. ie:

Currently there's no native equivalent for this type of dropdown and creating a component would add more time to this task. I'm going to keep this in mind but use Galleries instead, to create a similar experience. However, the UI overall in the scheduler tool needs attention, perhaps we can revisit this in the future when we allocate time to improve it.

**Comment by JonathanCrd** [comment]
I have started with the implementation of this new feature, here's the flow so far in the SDK Review app and some questions I have:

Added a "Release Plan" field under the "SubService" field. 
![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/8d66349f-6959-459c-beec-28f2c6e969de)

When a product is selected, the button becomes available
![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/8c3e5a24-5dbb-4b93-a984-efaf930552c2)

Clicking the button opens a panel that shows a list of all the `Not started` and `In progress` Release Plans for the specified product.
I left the completed and abandoned ones out on purpose.
![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/d90db432-0bf1-4d44-9f74-e8ac403b6b64)
In this example there's only one active release plan. I show some information to the user to help them identify what's the release plan they should use [marked in blue], **QUESTION: do you have any ideas on how we could improve this card? Like identifying what information might be helpful to show.**

When the user clicks Select, several actions happen:

- The app fetches the information from the `API Spec` work item and auto-populates the following inputs:
   - Hero scenarios link
   - Architecture diagram link
   - Core concepts doc link 
- The app also fetches the target languages that were specified in the SDK Release App.
  - It creates the artifacts for each language with an empty link.
  - The user can edit those artifacts, but cannot delete them, since they were provided by the release plan. However, they can add other languages there and they can only delete those.
  - **QUESTION: Should I allow the users to change the targeted languages in the scheduler? Or disable the option to add more languages/platforms if they have linked a release plan?**
  - **QUESTION: There are some languages/platforms shown in the scheduler that are not available in the Release Planner. Should we change this? **

![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/82b3c8e6-a98c-4ffc-a915-d63a5bac2ec1)
![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/117fecd6-61e1-46c5-aec3-f1936c51422a)

![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/ee5e11fe-98d9-49c9-9a9d-b36db661e481)

And this is how the Release Plan field looks like after that finished:
![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/e8989468-3f30-4693-a3eb-af1bacc9961f)

If the user clicks on change, the same panel appears, but this time the selected Release Plan is highligted.
![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/bf59c024-5b6a-48c7-8db2-1f065fe894d1)

If they remove the selected release plan, it does the same process as the "Select" option but inverse:

- All links fields get cleared.
- All created APIview artifacts are deleted.
- The auto-populated domains shown get deleted too, only keeping the ones added by the user.

When **updating a meeting,** the user can select a Release Plan if this was not specified. However, it cannot change the Release Plan if it was saved before. **QUESTION: Should I allow users to change Release Plans whenever they edit an existing review?**

To Do:
- [ ] Update the links in the Work Item when the meeting gets saved.
- [ ] Show a loading screen for the artifacts too.
- [ ] Add a visual guide to let the user know which data is coming from the release plan. **QUESTION: What would be better? A label at the bottom of the text-input saying something link "Auto-filled by release plan"? or some type of icon? I'm open to all ideas here.**

Sorry for the long text, I wanted to get all my assumptions written in case I'm missing a use-case.

**Comment by maririos** [comment]
@JonathanCrd 

> QUESTION: do you have any ideas on how we could improve this card? Like identifying what information might be helpful to show.
I like the information you are providing. When we add the `name` we should add it here too. But for now this is ok.

> Create a new release plan
The content should be: `A release plan is a guided workflow that you can use to track an upcoming REST API and SDK release`

> QUESTION: Should I allow users to change Release Plans whenever they edit an existing review?

What do you think? would it make sense? what would be the implications? 
If we are unsure, we can always leave it disabled and get feedback and see what the users want

> QUESTION: What would be better? A label at the bottom of the text-input saying something link "Auto-filled by release plan"? or some type of icon? I'm open to all ideas here.

Maybe as part of loading the data, the screen can say something like `Loading information from your release plan...` or something like that. and not in every single field that got updated.

> Can the user overwrite the information imported? i.e change the arch diagram link?

**Comment by JonathanCrd** [comment]
>  > QUESTION: Should I allow users to change Release Plans whenever they edit an existing review?
>
> What do you think? would it make sense? what would be the implications?
If we are unsure, we can always leave it disabled and get feedback and see what the users want

I'll enable it, then existing meetings can link their release plan.

> I believe this is true. But want to confirm with you

I believe the same, I'll let them edit them.
