### ISSUE TITLE
What to do if the Work Item ID for a Service or Product does not exist anymore

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#6841]
When onboarding a Service or Product, if the record has a Work Item ID we run `Get Release Work Item` to retrieve the work item details. However, while making changes in DEV I came across the scenario in which the ID saved in the database does not longer exists on ADO, and so the app was crashing, and the cloud flow was failing.

We should catch this and do something about it in case a user faces this scenario. In all cases we should catch this error and prevent the cloud flow for making retries.

Ideas:
- Show a warning to the user.
- Email the PM about it ("A user tried to onboard _X_ product, but work item #_0000_ was not found...)
- Create a new Work Item

**Comment by maririos** [comment]
There might be a cloud flow action that gets triggered when a work item gets deleted.  We could look into this  and also the "trash bin" to restore the work item

**Comment by praveenkuttappan** [comment]
I am not sure whether we need to handle this case. Manual cleanup of Epics was done earlier due to duplicate data when migrated to new work item model and accidentally deleted valid work item instead of duplicate ones. Do we still need to handle this? @ladonnaq Do you know if anyone still manually deletes the work item?

IF we still need to add a protective mechanism then a simple solution to catch this and inform is to create a cloud flow that gets triggered whenever a work item is deleted. We can send an email to Engagement experience team and PM team to notify if a work item that is referred in DB is deleted and inform them to restore it from work item trash bin.  We can extend this to other type of work items if they are referred in PowerApps DB. For e.g.  Service, Triage, Release plan and API version.

**Comment by maririos** [comment]
ping @ladonnaq 
>  Do we still need to handle this? @ladonnaq Do you know if anyone still manually deletes the work item?

**Comment by ladonnaq** [comment]
> ping [@ladonnaq](https://github.com/ladonnaq)
> 
> > Do we still need to handle this? [@ladonnaq](https://github.com/ladonnaq) Do you know if anyone still manually deletes the work item?

I think you can close this issue. I have not encountered this problem in a while.
