### ISSUE TITLE
Add question on Release plan creation about the type of SDK release they need

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6964]
- New beta
- New existing beta
- GA

**Comment by maririos** [comment]
@ladonnaq  could you add more information on how the UI will look like and the implication of this information? where should it be saved and all of that

**Comment by ladonnaq** [comment]
@maririos I created a new epic to track new requirements for the "create a release plan" feature.  I will work this month (Jan 2024) on writing the requirements and meeting with @JonathanCrd to discuss best approach to updating the UI to support.

**Comment by ladonnaq** [comment]
> > @maririos Mariana Rios Flores FTE I created a new epic to track new requirements for the "create a release plan" feature - #6930. I will work this month (Jan 2024) on writing the requirements and meeting with @JonathanCrd Jonathan Cardenas FTE to discuss best approach to updating the UI to support. As I continue to cleanup backlog (I own), I will move other relevant task to the list. If I see any duplicates, I will consolidate and close.
> 
> So should we close this issue?

We are asking beta or stable.  We need to add a question that ask if this is the "initial SDK release" so that way we ensure the release plan has the extra requirements for first initial beta and first initial stable releases.  I created a new issue and will define the requirements - https://github.com/Azure/azure-sdk-tools/issues/7550
