### ISSUE TITLE
[Release Planner] Options for published SDKs going off-screen

### ISSUE THREAD

**Issue by ccbarragan** [Azure/azure-sdk-tools#6989]
#### What's happening

The dropdown / combobox options go off screen in the **Onboard your product** > **SDK details** screen in Release Planner

#### Expected behavior

Options are visible and displayed under the combobox. For details, check out https://fluent2.microsoft.design/components/web/react/combobox/usage#behavior. 

#### Steps to reproduce

1. Click **Onboard product**.
2. Follow steps to **SDK details**.

#### Screenshots

<img width="1634" alt="CleanShot 2023-09-19 at 10 08 56@2x" src="https://github.com/Azure/azure-sdk-tools/assets/28902259/55d71eec-dc2e-4e2d-8121-9ad25525e648">

<img width="1728" alt="CleanShot 2023-09-19 at 10 08 11@2x" src="https://github.com/Azure/azure-sdk-tools/assets/28902259/f2dac7e1-6637-4f2d-9318-64b4dcd176f1">

**Comment by JonathanCrd** [comment]
I have fixed this on `DEV` by reducing the combo-box's width.

@ccbarragan this new combo-box is part of the new (preview) built-in modern control, which are not fully customizable. Since there are so many elements, the list shows next to it. 

I think there might be a better way to ask for this information, perhaps have a search-box and a list-box as the service configuration page:
![image](https://github.com/Azure/azure-sdk-tools/assets/17486462/f2007d72-6d5c-445e-b83c-895dc9918b35)

Or maybe a side-by-side list with the selected services and the whole list:
![image](https://github.com/Azure/azure-sdk-tools/assets/17486462/7608fdbd-15b6-4eae-bbdb-a9e95d6a7e85)

Maybe we could add filters per language too. 

I'm curious if there's is a better way for users to search and select their published SDKs, and if it is worth it to invest the time to improve it.

**Comment by praveenkuttappan** [comment]
This change is not required anymore. I have made a change to remove SDK package selection during onboarding a product to release planner.

**Comment by JonathanCrd** [comment]
@praveenkuttappan do you have the link of the GitHub issue for that change? I'd like to understand more why we're removing that question in this screen.
