### ISSUE TITLE
Add Release Plan overall status tag in the Dashboard view

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#7051]
In the Release Plan list we show the overall status of the release plan: "Not started", "In progress" or "Finished". As it can be seen here

![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/c626c281-ddcf-40db-a4d9-50b946d0a2db)

However, we don't have that in the summary view. It can be inferred by the milestones graph and list, but it is not explicit. Should we add the same label tag in this screen too?

**Comment by ccbarragan** [comment]
@JonathanCrd If users are already able to understand the status of a release plan from the summary view, I'd say having the tag is redundant (especially if it's already indicated in the list view). Unless it serves an explicit purpose for the user, recommend leaving it off to reduce noise. Design principle: less is sometimes more!

kinda off-topic, but instead of **Finished** status label I recommend using **Complete**.

**Comment by JonathanCrd** [comment]
> @JonathanCrd If users are already able to understand the status of a release plan from the summary view, I'd say having the tag is redundant (especially if it's already indicated in the list view). Unless it serves an explicit purpose for the user, recommend leaving it off to reduce noise. Design principle: less is sometimes more!
> 
> kinda off-topic, but instead of **Finished** status label I recommend using **Complete**.

Good point.

Regarding the label, that's coming from the database, so I opened this issue to keep track of it:

- https://github.com/Azure/azure-sdk-tools/issues/7062
