### ISSUE TITLE
Scheduler admins should be able to book a meeting whenever they want

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7137]
Currently there is a restriction that a slot is only available for booking if it is in > 2 days.
We have had cases where the admins want to move a meeting from one day to another, or book it per request of the users and they have to ping our team for it to happen.

We should bypass the restriction of the 2 days for admin users.

FYI @ronniegeraghty

**Comment by JonathanCrd** [comment]
Progress tracker
- [ ] SDK Review
- [ ] API Review
- [ ] Informational meeting

**Comment by JonathanCrd** [comment]
One minor caveat:

Due to the calendar original design, there's a possibility that the current day is going to show available for admins even if the available time has passed. However, admins will not be able to schedule a past meeting because the time will be disabled. Here is how it will look like:

![image](https://github.com/Azure/azure-sdk-tools/assets/17486462/81f3bc74-9f49-4782-83c3-a5e262b63c60)
_Screenshot took on Nov 15th 2023 15:03_

Also, added a `Admin mode` badge to make explicit the behaviour of the calendar.
Now, Admins can schedule or re-schedule any meeting without the 2 days restriction

**Comment by maririos** [comment]
FYI @ronniegeraghty this has been deployed to Prod :)
