### ISSUE TITLE
[Breaking Change][False positive] openapi-diff should filter out client parameters before checking parameter order

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#7170]
The `ChangedParameterOrder` rule should only fire when the order of the parameters for the method -- parameters not marked with `x-ms-parameter-location: client` change.

This rule triggers many false breaking change errors for some API definitions that are converted from OpenAPI to TypeSpec, e.g.

https://github.com/Azure/azure-rest-api-specs/pull/25569

**Comment by konrad-jamrozik** [comment]
- [doc for `x-ms-parameter-location`](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-parameter-location)

Basically, this rule says that when generating language (e.g. C#) SDK clients, the parameter will either be a C# property on the client class (value: `client`), or it will be a C# method parameter on the C# client (value: `method`).

@mikekistler you wrote:

> The `ChangedParameterOrder` rule should only fire when the order of the parameters for the method -- parameters not marked with `x-ms-parameter-location: client` change.

I understand that **strictly** speaking you wanted to say:

> The `ChangedParameterOrder` rule should only fire only on parameters with `x-ms-parameter-location: method` property.

Correct?

What you said is effectively equivalent a little bit by coincidence. This is because:

- When a parameter has no `x-ms-parameter-location`, its value is by default `client` so order doesn't matter
- When a parameter has `x-ms-parameter-location` set to `client`, then its order doesn't matter.
- The only other remaining valid case is when `x-ms-parameter-location` is set to `method`, and this is the only case when the order matters.

Correct?

**Comment by mikekistler** [comment]
All correct.
