### ISSUE TITLE
Add service contact information into the codeowners files

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7302]
Asks are:
- Having at least one team member added to CODEOWNERS as a PR reviewer.
- Having at least one team member added to CODEOWNERS as a Service Owner.

Requirement questions:
- Where do these files live? is this per language?
- How should the user do this?
- Where in the process should this happened? I don't consider onboarding the right place as the user might not even do SDKs, or it might be too early fro them to know this information. Will it be too much to put in the `Create a release plan`?
- How should the existing information be reconciled with the Release Planner? what is the link? I really doubt codeowners is integrated with Service Tree to be able to give us a unique identifier and a clear link between both worlds

**Comment by jsquire** [comment]
> Where do these files live? is this per language?

Every repository has a CODEOWNERS file in its `.github` directory.   Example:
https://github.com/Azure/azure-sdk-tools/blob/main/.github/CODEOWNERS

Each copy is unique.  Teams usually have different points of contact for different languages.

> How should the user do this?

Open a pull request with the changes to CODEOWNERS.   Rather than using individuals as we had in the past, I believe that we're recommending they create a GitHub team and manage their members there.  @ronniegeraghty would be able to confirm. 

> Where in the process should this happened? I don't consider onboarding the right place as the user might not even do SDKs, or it might be too early fro them to know this information. Will it be too much to put in the Create a release plan?

Great question.   This is another one for @ronniegeraghty.    From the pragmatic perspective, this needs to be in place before they merge their first pull request.   We'd prefer that it NOT be done as part of that pull request so that the right reviewers can review.

> How should the existing information be reconciled with the Release Planner? what is the link? I really doubt codeowners is integrated with Service Tree to be able to give us a unique identifier and a clear link between both worlds

I don't know what half of that means so, uh, @ronniegeraghty?

**Comment by ronniegeraghty** [comment]
> How should the user do this?
>Open a pull request with the changes to CODEOWNERS. Rather than using individuals as we had in the past, I believe that we're recommending they create a GitHub team and manage their members there. @ronniegeraghty would be able to confirm.

Our advice in the past for teams who don't want to list a specific GH user that they create a new GH account using a DL as the email address so the whole DL gets alerted when the GH user is mentioned. (I don't know if this would work for PR approvals since it will require someone to sign into that group GH user. 
Do we know if it's possible to mention a GitHub Team? As well as list them as a CODEOWNER for approvals? We might just have to test this ourselves. 

> Where in the process should this happened? I don't consider onboarding the right place as the user might not even do SDKs, or it might be too early fro them to know this information. Will it be too much to put in the Create a release plan?
Great question. This is another one for @ronniegeraghty. From the pragmatic perspective, this needs to be in place before they merge their first pull request. We'd prefer that it NOT be done as part of that pull request so that the right reviewers can review.

I believe it should be a step in the release planner. Maybe we should have a meeting where @jsquire and I can be taken through the release planner steps and recommend the best place for this step. I believe this would also be a good time to make the teams aware of our customer issue SLAs. 

>How should the existing information be reconciled with the Release Planner? what is the link? I really doubt codeowners is integrated with Service Tree to be able to give us a unique identifier and a clear link between both worlds
I don't know what half of that means so, uh, @ronniegeraghty?

@maririos, how does the release planner work with existing teams who want to release a new version of a library? Maybe we can work a step into the process of releasing new versions of existing libraries that checks if the information has been added or even asks the team to reconfirm the data before releasing a new version.

**Comment by maririos** [comment]
> Our advice in the past for teams who don't want to list a specific GH user that they create a new GH account using a DL as the email address so the whole DL gets alerted when the GH user is mentioned. (I don't know if this would work for PR approvals since it will require someone to sign into that group GH user.

Great!! @ronniegeraghty is there documentation about this so we can point people to it?

**Comment by maririos** [comment]
Also, meeting scheduled so we can talk more about the flow and where should the information be

**Comment by ronniegeraghty** [comment]
> > Our advice in the past for teams who don't want to list a specific GH user that they create a new GH account using a DL as the email address so the whole DL gets alerted when the GH user is mentioned. (I don't know if this would work for PR approvals since it will require someone to sign into that group GH user.
> 
> Great!! @ronniegeraghty is there documentation about this so we can point people to it?

This is what we have now: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-customer-support
Will want to update with the guidance to use a GH team now.

**Comment by maririos** [comment]
@ronniegeraghty questions:
- The request is to tell people "hey there is this file, make sure someone from your team is added." Is this accurate? do you have a specific message I should use? 
- Could you remind me here where do we want this to show? is it when they are generating the SDKs? or after they release?
- This is per language, right?
- I am going to link to the document you shared. Anything specific you would like me to add?

**Comment by maririos** [comment]
> [@ronniegeraghty](https://github.com/ronniegeraghty) questions:
> 
> * The request is to tell people "hey there is this file, make sure someone from your team is added." Is this accurate? do you have a specific message I should use?
> * Could you remind me here where do we want this to show? is it when they are generating the SDKs? or after they release?
> * This is per language, right?
> * I am going to link to the document you shared. Anything specific you would like me to add?

I think the answers are here: https://github.com/Azure/azure-sdk-tools/issues/7351 so I am going to close this issue

**Comment by ronniegeraghty** [comment]
> * The request is to tell people "hey there is this file, make sure someone from your team is added." Is this accurate? do you have a specific message I should use?

Yes. In my ideal scenario we some how check to make sure their service has a valid CODEOWNER listed for each language. Not sure how that type of check would be performed from the release planner. 
Here's a sample message you could use: 
`To make sure issues and pull request for your libraries are properly routed to your team, add/revalidate code owners for your libraries in each of our language repos.  Instructions on this process are located [here in the "Getting mentioned on issues" section](https://eng.ms/docs/products/azure-developer-experience/develop/sdk-customer-support#getting-mentioned-on-issues).

> * Could you remind me here where do we want this to show? is it when they are generating the SDKs? or after they release?

This needs to be before the release and ideally before they open their first PR. Or the changes to `CODEOWNERS` is in their first PR. I believe this is as they begin generating libraries. 

> * This is per language, right?

Yup. They need to do this in each language repo. 

> * I am going to link to the document you shared. Anything specific you would like me to add?

Only maybe that the instructions for this task are specifically in the "Getting mentioned on issues" section.

**Comment by maririos** [comment]
@ronniegeraghty thank you :)
