### ISSUE TITLE
Convert `azure-rest-api-specs-pipeline` to builds directly on the `azure-rest-api-specs` repository

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#7414]
I had a discussion last night with @mikeharder and then another discussion this morning with @maririos ....what would it take to get all of the complication out of the `azure-rest-api-specs` checks?

When I say `checks` here, I'm specifically referring to the Swagger validation pipeline checks that trigger on an spec PR: `ModelValidation, LintDiff, BreakingChange, etc`.

The complication of the `pipeline-bot` infrastructure makes it difficult to debug outages, and the core checks really don't need a bot to ask them to run.

**What is blocking us from moving swagger validation checks to pure devops checks?**

**Comment by kurtzeborn** [comment]
We discussed this in triage today.  Yes this is a good idea and we are incrementally getting there (typespec validation as an example).  There are other things like the downstream code generation pipelines which can't be cleanly split out from the checks (or arguably they already are as separate pipelines).

So we are already headed in this direction, but it will be a huge undertaking to get everything out.  I'm going to close this issue, but that doesn't mean we're not doing this.  Konrad is already working on refactoring breaking changes tools and labeling workflows so that they are simpler and the complication is out of the pipeline.  We will tactically choose other to do the same thing.  Trying to do them all at once, hackathon style, would take weeks and take the engineering system team offline to get it done.  It would also likely be very destabilizing to the system.

CC: @weshaggard, @benbp, @maririos
