### ISSUE TITLE
[SDK azure-sdk-for-js] Step PublishTestResults fails with OOM

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#7458]
Step `PublishTestResults` in pipeline "SDK azure-sdk-for-js" is failing with an out-of-memory error:

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3342845&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=8bb9d4f3-9b43-540e-854d-84d9721cb6e9

**Comment by raych1** [comment]
Hi @jeremymeng , @qiaozha told me that you are the owner of JS pipelines. I'm adding you to this issue.

`max-old-space-size` is already set to 8GB but sometimes this OOM issue will still happen. It looks like JS language has larger size test result files than the other languages. Do you think if some test result of JS can be excluded from publishing step?

**Comment by jeremymeng** [comment]
@raych1 The `PublishTestResults` step are trying to [upload '*_junit.xml' files](https://github.com/Azure/azure-rest-api-specs-pipeline/blob/54c219f8ae12b689c1c7bab25651f8e602d26c02/.azure-pipelines/templates/AfterTask.yml#L20). Our JS SDK tests only output to 'test-results.xml' and 'test-results.browser.xml' files. So the OOM is unlikely caused by JS SDK test result files.  It's possible that there's some bug in the PublishTestResults task so that it doesn't work well with with JS SDK repo?

Also, looking at the above result, none of other languages has '*_junit.xml' report files either.  So maybe it isn't important to publish tests results in this pipeline and we could skip this step?

**Comment by raych1** [comment]
This step has been removed from the pipeline.
