### ISSUE TITLE
Runtime Exception in Swagger BreakingChange PR check

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#7699]
The Swagger BreakingChange PR check is failing with a funky runtime exception in PR [17104](https://github.com/Azure/azure-rest-api-specs-pr/pull/17104):

<img width="838" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/85643503/a697cbc9-384f-4280-a109-b49669a9b8bb">

> You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize( 'lib/mappings.wasm': ... ) before using SourceMapConsumer

**Comment by mikekistler** [comment]
Also occurring in https://github.com/Azure/azure-rest-api-specs/pull/27505

**Comment by konrad-jamrozik** [comment]
Thanks for reporting and sorry for the issue. This should be fixed by now:

[Konrad Jamrozik: MITIGATED INCIDENT. Please run `/azp run` to unblock your PR if y...](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1708111432914?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1708111432914&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1708111432914)
posted in Azure SDK / API Spec Review on Friday, February 16, 2024 11:23 AM
