### ISSUE TITLE
tsp-client fails when using a local typespec project with commit hashes that aren't on the remote

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk-tools#7721]
It appears `tsp-client` expects the value in `tsp-location.yaml` to point to a live hash on github. I am using `tsp-compile` to initialize a new library. I'm working from a local checkout of a PR into `azure-rest-api-specs` that I have made a commit to. I hit this failure:

```
Found emitter package @azure-tools/typespec-java
SDK initialized in D:/source/azure-sdk-for-java/sdk/eventgrid/azure-messaging-eventgrid-systemevents/sdk/eventgrid/azure-messaging-eventgrid-systemevents
Error: fatal: remote error: upload-pack: not our ref fa98e8d88df580b0a560143da8166d859255056d
fatal: remote error: upload-pack: not our ref fa98e8d88df580b0a560143da8166d859255056d
fatal: remote error: upload-pack: not our ref fa98e8d88df580b0a560143da8166d859255056d
fatal: remote error: upload-pack: not our ref fa98e8d88df580b0a560143da8166d859255056d
fatal: reference is not a tree: fa98e8d88df580b0a560143da8166d859255056d
```

repro steps (I think):
1) Make a local sync of some typespec project
2) Make a change to that project and commit it
3) run `tsp-client init -c <path to local project> --repro Azure/azure-rest-api-specs --commit <local commit>`

**Comment by catalinaperalta** [comment]
I'll keep this issue open for tracking to improve the command descriptions in the README.

**Comment by billwert** [comment]
Hey! The target directory did not exist in this case and it was the first time I had run init for it.

**Comment by catalinaperalta** [comment]
Ah I see, this line in the output had caught my eye so realized there was also an issue when running the init: `SDK initialized in D:/source/azure-sdk-for-java/sdk/eventgrid/azure-messaging-eventgrid-systemevents/sdk/eventgrid/azure-messaging-eventgrid-systemevents
`.  

About the local commit, tsp-location.yaml is meant to help with versioning control for specs checked in upstream in the `azure-rest-api-specs` repo, so it's not really meaningful to put a local commit in that file (could also lead to some issues if the file is ever accidentally checked in with a local commit since we do run CI checks based off of the contents of tsp-location.yaml). If this is a scenario where we're actively testing some changes locally before we check them into the repo, then we should just refer to the local spec clone and iterate based on those changes. So if you have some work your testing on a local clone of the spec repo, then we would just use `tsp-client update --local-spec-repo <path to the TypeSpec project in the local clone>`.

**Comment by catalinaperalta** [comment]
We added more flexibility in tsp-client so that the repo and commit arent required anymore during init as of v0.14.0. Here are some docs on the simplified local-spec-repo init scenario: https://azure.github.io/typespec-azure/docs/howtos/generate-with-tsp-client/local_spec_quickstart/
