### ISSUE TITLE
Sparse checkout errors sporadically in CI

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-tools#7932]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=3624149&view=logs&j=51b3775a-1644-5866-7147-5315708e6c48&t=25d16842-582d-5a38-69fc-328226e341e6&l=27

**Comment by benbp** [comment]
We've been seeing these github timeouts lately, they seem to be concentrated on mac agents.

Error for posterity:

```
git -c advice.detachedHead=false checkout f46af6905e9370aed03578e6fc4ec76249c8a64d --
fatal: unable to access 'https://github.com/Azure/azure-sdk-for-net/': Recv failure: Operation timed out
fatal: could not fetch fbfa86eb878a414caeb5e0ab7d1020d13ea5a9e4 from promisor remote

##[error]PowerShell exited with code '1'.

```

**Comment by danieljurek** [comment]
Mac hosted agents aren't hosted in Azure Datacenters. They're hosted in [GitHub datacenters](https://learn.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops). This means that these agents could be impacted by a combination of factors including both Azure and GitHub connectivity. 

Since these issues relate to network connectivity and don't directly test SDK/product functionality, I think a reasonable thing to do here would be to detect these kinds of failures (either by checking exit codes or the outputs) and re-trying, after a delay, on failures that could be transient.

**Comment by benbp** [comment]
@danieljurek https://github.com/Azure/azure-sdk-tools/pull/8019
