### ISSUE TITLE
Create a test pipeline for our eng/common changes

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#830]
As we get more and more pipelines depending on stuff from `eng/common` and we need to have a way to test these changes in the tools repo itself to help ensure we don't break things. 

I'm starting to think that we might want to have a wrapper pipeline that applies the changes to each of our core language repos and does a build and publish pipeline build for the template project in each repo. This might take a little time but it will allow us to build up our confidence in the changes and help eliminate a bunch of manually testing we currently have to do to verify changes. 

@azure/azure-sdk-eng does that sound like a reasonable plan? Anyone have any other ideas?

**Comment by scbedd** [comment]
@weshaggard I have been thinking about this all week. You're right on the money and this will save us a lot of pain.

Maybe we simply add a conditional step to our pipelines that can pull the merge commit from a PRNumber, and apply the `eng.common` changes to the locally checked out repository for the build?

**Comment by JimSuplizio** [comment]
I'm not sure if outside of actually building and releasing something the changes would even be fully tested. For example, I know the changelog verification stuff has different behavior whether it's being run as part of the regular build process versus a release task. The docs tasks (ms and github.io) as well as the version increment tasks are in a similar boat because those code paths really aren't exercised outside of releasing a library. Java has a template library (and a template BOM) which is the library used for testing release pipeline stuff for Java. Do the other language have something similar?

**Comment by weshaggard** [comment]
So I chatted with @chidozieononiwu a little bit more and what we are currently thinking is something like:

- Instead of using a post commit sync of eng/common like we do today we will create move the sync to happen as part of a PR to the tools repo that makes any changes under eng/common. 
  - We will scope those PR's to only contain the latest changes that are in the tools PR. Note multiple parallel tools PRs might occur but that should be OK as we can test them in isolation. 
- We will add additional test pipelines in the languages repos that will trigger when there are any changes under eng\common.
  - These will likely be the template (or equivalent) pipeline in each repo
  - It will trigger the template pipeline in a mode that will automatically do a release of the template package as well. We need to think about how we protect this automatic releasing based on PR validation.

That will both get our eng/common changes moved forward which will decrease the common testing workflow (i.e. copy the tools changes in each language repo and do validation there) and decrease human error in copying those changes around.  It will also get us better validation on changes in the language repos. The new release template pipeline should probably trigger for any yml file changes in the language repos.

**Comment by JimSuplizio** [comment]
I like the approach we're thinking about here.

> It will trigger the template pipeline in a mode that will automatically do a release of the template package as well. 

So, I don't know if it matters or not if the release is automatically triggered or the pipeline is manually triggered considering it would require approval at the release step anyways.  At a minimum the pipeline build should be sufficient enough to test many of the changes with the release only being necessary in specific situations. Whomever is making the changes should know if the release is necessary to test them or not.

**Comment by chidozieononiwu** [comment]
An interesting question is what should we do about repos that don't yet have template packages?

**Comment by weshaggard** [comment]
If they don't yet have a template package then we should create one for the repo, or at least create a test pipeline that will allow us to validate all the steps through release.

**Comment by chidozieononiwu** [comment]
Based in feedback from various people about noisy sync PRs that are left unattended to for long periods of time. We are reworking the eng/common sync workflow to delay the creation of pull requests till changes are properly tested via the release of the template package. This means that the sync pipeline will now also trigger test (template) pipelines for the various languages and only after successful run of all the test pipelines will the sync PR be created. The workflow will now look like this.

1. `Create a PR (Tools PR) in the 'azure - sdk - tools' Repo` with changes to eng/common directory
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8595;
2. `azure-sdk-tools - sync - eng-common` pipeline is triggered for the Tools PR
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8595;
3. `The sync pipeline queues test (template) pipelines for each language` net, js, java, python template pipelines.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8595;
4. `Test pipelines release respective template packages` You'll have to approve the release to pass the approval gate. The test (temlate) pipeline will automatically release the next eligible version without needing manual intervention.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8595;
5. `Repeat step 1 - 4 by pushing new changes to your Tools PR` Do this till you have satisfactory test runs all the way to release of the template package.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8595;
5. `Sign off on next stage of the sync pipeline using the approval gate` The CreateSyncPRs stage will create the sync PR in the various language repos.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8595;
5. `Approve all Sync PRs then sign off on the last stage of the sync pipeline` The VerifyAndMerge will merge all your sync PRs into the language repo. There should be no need for delay here since you already tested with test (template) releases.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8595;
5. `Finally Merge your Tools PR`

**Comment by mitchdenny** [comment]
Excellent stuff ... and thanks for the very through explanation of the workflow. It would be great to get this procedure documented on the wiki as well so we can point other team members to it as well.
