### ISSUE TITLE
Update management plane "Generate SDK" to remove extra steps

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8300]
After changes done last week, extra steps where added to the generation of the management plane SDKs (for languages different than .NET) that don't make sense because the service team will only have the SDK when they request a release.

Also, the link used for the Release request documentation doesn't make sense anymore because it takes people to create a release plan. Instead, we should tell users to go to the next step and request a release.

See in red the steps to remove and in yellow the link to remove:
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/edbcfc7b-ed58-4d70-bee2-5f6fff0b16da)

**Comment by maririos** [comment]
FYI @praveenkuttappan I went ahead and made the changes so now it looks like:

![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/484a7600-1b5c-41f0-88ca-a0fcea861e91)

**Comment by praveenkuttappan** [comment]
We can also remove Generate SDK step itself. Right?

**Comment by praveenkuttappan** [comment]
@maririos Generate SDK for non .NET looks like below now.

![image](https://github.com/Azure/azure-sdk-tools/assets/55455725/c830ae1c-815a-4a49-b28b-2bf2304f4b36)

**Comment by ladonnaq** [comment]
> We can also remove Generate SDK step itself. Right?

We could streamline the process by only including the .NET language. However, we should inform users that SDKs for other languages will be generated and released during the Release SDK step. We should not use the phrase "generated automatically" because that is inaccurate. There is a member of the management plane team (vendor) responsible for generating and releasing the management plane SDKs.
