### ISSUE TITLE
azure-rest-api-specs automation is removing BreakingChange-Approved-Previously label

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#8494]
In PR https://github.com/Azure/azure-rest-api-specs/pull/29527, the AzureRestApiSpecReview bot removed the `BreakingChange-Approved-Previously` label.

<img width="810" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/85643503/5cf86b8a-c024-413e-8ddf-57d3eef9c0f9">

Perhaps this happened because it also removed the `BreakingChangeReviewRequired` label -- that makes sense -- except that on the very next run of the pipeline (without any intervening commits) it added `BreakingChangeReviewRequired` back.

So we either need to fix whatever problem caused it to _not_ see the breaking change in the first run or simply leave the `Approved` label in place -- the latter is probably the easier and more reliable fix.

**Comment by konrad-jamrozik** [comment]
@mikekistler I see from the logs this was the old implementation of the breaking change tooling, before the recent simplification I did. It is not worth for me to try to debug what was it, as the code has since changed a lot and quite possibly I fixed whatever was the problem along the way. Let me know if this happens in new PR. For now I am closing.
